Repository testcontainers/testcontainers-dotnet, pull requests merged in 2022-11, with the labels that each got.

#652 feat(#640): Add WithResourceMapping
  .github/workflows/cicd.yml
  CHANGELOG.md
  docs/api/create_docker_container.md
  src/Testcontainers/Builders/BuildConfiguration.cs
  src/Testcontainers/Builders/ITestcontainersBuilder.cs
  src/Testcontainers/Builders/TestcontainersBuilder.cs
  src/Testcontainers/Builders/TestcontainersBuilderDatabaseExtension.cs
  src/Testcontainers/Clients/DefaultLabels.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Configurations/Containers/ITestcontainersConfiguration.cs
  src/Testcontainers/Configurations/Containers/TestcontainersConfiguration.cs
  src/Testcontainers/Configurations/Modules/Databases/ElasticsearchTestcontainerConfiguration.cs
  src/Testcontainers/Configurations/Modules/HostedServiceConfiguration.cs
  src/Testcontainers/Configurations/Volumes/BinaryResourceMapping.cs
  src/Testcontainers/Configurations/Volumes/FileResourceMapping.cs
  src/Testcontainers/Configurations/Volumes/IResourceMapping.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/CopyResourceMappingContainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/ReadFileFromContainerTest.cs
Labels: enhancement

#661 chore(#654): Update CHANGELOG.md, refactore TestcontainerNetworkBuilderTest
  CHANGELOG.md
  src/Testcontainers/Builders/ITestcontainersNetworkBuilder.cs
  src/Testcontainers/Builders/TestcontainersNetworkBuilder.cs
  src/Testcontainers/Clients/DockerNetworkOperations.cs
  src/Testcontainers/Configurations/Networks/TestcontainersNetworkConfiguration.cs
  src/Testcontainers/Networks/NonExistingDockerNetwork.cs
  tests/Testcontainers.Tests/Unit/Networks/TestcontainerNetworkBuilderTest.cs
Labels: chore

#660 refactor: Normalize container paths to forward slashes
  build.cake
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Configurations/Images/ImageFromDockerfileConfiguration.cs
  src/Testcontainers/Configurations/Modules/Databases/ElasticsearchTestcontainerConfiguration.cs
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  src/Testcontainers/Guard.Null.cs
  src/Testcontainers/Guard.String.cs
  src/Testcontainers/Images/DockerfileArchive.cs
  src/Testcontainers/Logging.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/CopyResourceMappingContainerTest.cs
Labels: chore

#667 chore: Use TargetFrameworks (plural) to write the output to its corresponding target framework subdirectory
  examples/WeatherForecast/Directory.Build.props
  examples/WeatherForecast/src/WeatherForecast/WeatherForecast.csproj
  examples/WeatherForecast/tests/WeatherForecast.InProcess.Test/WeatherForecast.InProcess.Test.csproj
  examples/WeatherForecast/tests/WeatherForecast.Test/WeatherForecast.Test.csproj
  tests/Testcontainers.ResourceReaper.Tests/Testcontainers.ResourceReaper.Tests.csproj
  tests/Testcontainers.Tests/Testcontainers.Tests.csproj
Labels: chore

#668 fix: Rename coverage.json to coverage.net6.0.json to merge with the correct file
  Packages.props
  build.cake
  src/Testcontainers/Guard.Null.cs
  tests/Testcontainers.Tests/Testcontainers.Tests.csproj
  tests/Testcontainers.Tests/Unit/Clients/TestcontainersConfigurationConverterTest.cs
Labels: bug

#657 docs: Add how to configure a container start and apps or services
  docs/api/create_docker_container.md
Labels: documentation

#663 docs: Add network communication
  docs/api/create_docker_container.md
  docs/api/create_docker_network.md
  examples/WeatherForecast/README.md
Labels: documentation

#671 fix(#650): Update SharpZipLib to version 1.4.1 to prevent a deadlock in the Docker container image build
  CHANGELOG.md
  Packages.props
  examples/WeatherForecast/Directory.Build.props
  examples/WeatherForecast/Dockerfile
  examples/WeatherForecast/README.md
  examples/WeatherForecast/WeatherForecast.sln
  examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecast.InProcess.Tests.csproj
  examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecastTest.cs
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecast.Tests.csproj
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastContainer.cs
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastImage.cs
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastTest.cs
  src/Testcontainers/Testcontainers.csproj
Labels: bug, dependencies

#674 Minor fixes to cake scripts
  .cake-scripts/parameters.cake
  .cake-scripts/version.cake
Labels: chore

#677 DockerImageNotFoundException when logged in into Docker Desktop
  CHANGELOG.md
  src/Testcontainers/Builders/DockerRegistryAuthenticationProvider.cs
  src/Testcontainers/Clients/DockerSystemOperations.cs
  src/Testcontainers/Clients/IDockerSystemOperations.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/ProtectDockerDaemonSocketTest.cs
Labels: bug

#684 Add default logger implementation
  CHANGELOG.md
  src/Testcontainers/Builders/AbstractBuilder.cs
  src/Testcontainers/Builders/DockerEndpointAuthenticationProvider.cs
  src/Testcontainers/Clients/DockerImageOperations.cs
  src/Testcontainers/Clients/TraceProgress.cs
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  src/Testcontainers/Containers/TestcontainersContainer.cs
  src/Testcontainers/Logger.cs
  src/Testcontainers/Logging.cs
  src/Testcontainers/Networks/NonExistingDockerNetwork.cs
  tests/Testcontainers.Tests/CustomSerilogLoggerFactory.cs
  tests/Testcontainers.Tests/Fixtures/Images/IgnoreFileFixture.cs
  tests/Testcontainers.Tests/Initialization.cs
  tests/Testcontainers.Tests/Initialized.cs
  tests/Testcontainers.Tests/SkipOnLinuxEngineAttribute.cs
  tests/Testcontainers.Tests/Unit/Configurations/DockerEndpointAuthenticationProviderTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/DockerRegistryAuthenticationProviderTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/TestcontainersAccessInformationTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/AzuriteTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/CosmosDbTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/CouchDbTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/CouchbaseTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/ElasticsearchTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/MariaDbTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/MongoDbTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/MsSqlTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/MySqlTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/Neo4jTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/OracleTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/PostgreSqlTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/RedisTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/MessageBrokers/KafkaTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/MessageBrokers/LocalStackTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/MessageBrokers/RabbitMqTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerCancellationTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Windows/TestcontainersContainerTest.cs
  tests/Testcontainers.Tests/Unit/Images/IgnoreFileTest.cs
  tests/Testcontainers.Tests/Unit/Images/ImageFromDockerfileTest.cs
  tests/Testcontainers.Tests/Unit/Networks/TestcontainersNetworkTest.cs
  tests/Testcontainers.Tests/Unit/Volumes/TestcontainersVolumeTest.cs
Labels: enhancement

#690 chore: sync governance files
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
  .github/settings.yml
Labels: chore

#687 docs: Update section Enable logging
  docs/custom_configuration/index.md
Labels: documentation

#691 feat: Add Docker host and socket override custom configuration
  docs/custom_configuration/index.md
  src/Testcontainers/Configurations/CustomConfiguration.cs
  src/Testcontainers/Configurations/EnvironmentConfiguration.cs
  src/Testcontainers/Configurations/ICustomConfiguration.cs
  src/Testcontainers/Configurations/PropertiesFileConfiguration.cs
  src/Testcontainers/Containers/ResourceReaper.cs
  tests/Testcontainers.Tests/Unit/Configurations/CustomConfigurationTest.cs
Labels: enhancement

#692 Feature/683 resolve hostname from first network
  CHANGELOG.md
  src/Testcontainers/Containers/TestcontainersContainer.cs
Labels: enhancement

#693 Waiting for healthy container when HEALTCHECK is defined
  src/Testcontainers/Configurations/WaitStrategies/ContainerDidNotStartException.cs
  src/Testcontainers/Configurations/WaitStrategies/IWaitForContainerOS.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilContainerIsHealthy.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitForContainerOS.cs
  src/Testcontainers/Containers/IDockerContainer.cs
  src/Testcontainers/Containers/TestcontainersContainer.cs
  src/Testcontainers/Containers/TestcontainersHealthStates.cs
  tests/Testcontainers.Tests/Assets/.dockerignore
  tests/Testcontainers.Tests/Assets/healthWaitStrategy/Dockerfile
  tests/Testcontainers.Tests/Assets/healthWaitStrategy/loop.sh
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilContainerIsHealthyTest.cs
Labels: enhancement

#695 feat(#678): Add support of custom configuration TESTCONTAINERS_HOST_OVERRIDE and TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE
  CHANGELOG.md
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  src/Testcontainers/Containers/ResourceReaper.cs
  src/Testcontainers/Containers/TestcontainersContainer.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/ResourceReaperCancellableTest.cs
Labels: enhancement

#698 chore(#531): Update CHANGELOG.md, fix minor project inconsistencies
  .gitattributes
  CHANGELOG.md
  README.md
  src/Testcontainers/Configurations/WaitStrategies/ContainerDidNotStartException.cs
  src/Testcontainers/Configurations/WaitStrategies/IWaitForContainerOS.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilContainerIsHealthy.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitForContainerOS.cs
  src/Testcontainers/Containers/IDockerContainer.cs
  src/Testcontainers/Containers/TestcontainersContainer.cs
  src/Testcontainers/Containers/TestcontainersHealthStates.cs
  src/Testcontainers/Containers/TestcontainersHealthStatus.cs
  tests/Testcontainers.Tests/Assets/healthWaitStrategy/Dockerfile
  tests/Testcontainers.Tests/Assets/healthWaitStrategy/docker-entrypoint.sh
  tests/Testcontainers.Tests/Assets/healthWaitStrategy/loop.sh
  tests/Testcontainers.Tests/Fixtures/Images/HealthCheckFixture.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilContainerIsHealthyTest.cs
Labels: chore
