Repository testcontainers/testcontainers-dotnet, pull requests merged in 2022-12, with the labels that each got.

#699 refactor: Run database container on web app start up if connection string is missing, replace mssql/server with azure-sql-edge
  examples/WeatherForecast/Packages.props
  examples/WeatherForecast/README.md
  examples/WeatherForecast/src/WeatherForecast/DatabaseContainer.cs
  examples/WeatherForecast/src/WeatherForecast/DatabaseContainerConfiguration.cs
  examples/WeatherForecast/src/WeatherForecast/Program.cs
  examples/WeatherForecast/src/WeatherForecast/WeatherForecast.csproj
  examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecast.InProcess.Tests.csproj
  examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecastTest.cs
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecast.Tests.csproj
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastContainer.cs
  src/Testcontainers/Containers/ResourceReaperState.cs
Labels: chore

#697 Updated docs with HEALTHCHECK wait strategy
  docs/api/wait_strategies.md
Labels: documentation

#701 docs: Fix Docker docs HEALTHCHECK link
  docs/api/wait_strategies.md
Labels: documentation

#703 feat: Prepare Resource Reaper (Ryuk) Windows support
  CHANGELOG.md
  src/Testcontainers/Builders/ITestcontainersBuilder.cs
  src/Testcontainers/Builders/TestcontainersBuilder.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Configurations/Modules/HostedServiceConfiguration.cs
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  src/Testcontainers/Configurations/Volumes/MountType.cs
  src/Testcontainers/Containers/IDockerContainer.cs
  src/Testcontainers/Containers/ResourceReaper.cs
  tests/Testcontainers.ResourceReaper.Tests/DefaultResourceReaperTest.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/VolumeFixture.cs
  tests/Testcontainers.Tests/SkipOnLinuxEngineAttribute.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/ResourceReaperCancellableTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/ResourceReaperTest.cs
Labels: enhancement

#708 Bugfix/648 do not ignore dockerfile or dockerignore
  CHANGELOG.md
  src/Testcontainers/Images/DockerIgnoreFile.cs
  src/Testcontainers/Images/DockerfileArchive.cs
  tests/Testcontainers.Tests/Assets/.dockerignore
  tests/Testcontainers.Tests/Unit/Images/ImageFromDockerfileTest.cs
Labels: bug

#709 feat(#694): Add Ryuk container privileged custom configuration
  docs/custom_configuration/index.md
  src/Testcontainers/Configurations/CustomConfiguration.cs
  src/Testcontainers/Configurations/EnvironmentConfiguration.cs
  src/Testcontainers/Configurations/ICustomConfiguration.cs
  src/Testcontainers/Configurations/PropertiesFileConfiguration.cs
  src/Testcontainers/Containers/ResourceReaper.cs
  tests/Testcontainers.Tests/Unit/Configurations/CustomConfigurationTest.cs
Labels: enhancement

#710 feat(#694): Add Resource Reaper (Ryuk) privileged mode support
  CHANGELOG.md
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  src/Testcontainers/Containers/ResourceReaper.cs
Labels: enhancement

#711 feat: Prepare next release cycle (2.4.0)
  .cake-scripts/version.cake
  .github/release-drafter.yml
  .github/workflows/cicd.yml
  CHANGELOG.md
  Directory.Build.props
  docs/api/wait_strategies.md
  src/Testcontainers/Containers/Modules/Databases/CouchbaseTestcontainer.cs
Labels: chore

#714 chore: Reduce concurrent builds
  .github/workflows/cicd.yml
Labels: chore

#717 Feature/715 add http wait strategy
  docs/api/create_docker_container.md
  docs/api/create_docker_image.md
  docs/api/wait_strategies.md
  src/Testcontainers/Configurations/WaitStrategies/HttpWaitStrategy.cs
  src/Testcontainers/Configurations/WaitStrategies/IWaitForContainerOS.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitForContainerOS.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitForContainerUnix.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitForContainerWindows.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilHttpRequestIsSucceededTest.cs
Labels: enhancement

#720 feat: Include file path in TarException: Entry closed at [...] (Docker build)
  src/Testcontainers/Images/DockerfileArchive.cs
Labels: enhancement

#721 fix: Remove Sonar finding csharpsquid:S6444
  src/Testcontainers/Configurations/WaitStrategies/UntilMessageIsLogged.cs
  src/Testcontainers/Images/DockerfileArchive.cs
  src/Testcontainers/Images/IgnoreFile.cs
Labels: chore

#724 chore: Replace SharpZipLib TarArchive helper class with TarOutputStream
  .github/workflows/cicd.yml
  .github/workflows/codeql-analysis.yml
  src/Testcontainers/Clients/DockerImageOperations.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Images/DockerIgnoreFile.cs
  src/Testcontainers/Images/DockerfileArchive.cs
  src/Testcontainers/Images/ITarArchive.cs
  tests/Testcontainers.Tests/Unit/Images/ImageFromDockerfileTest.cs
Labels: enhancement
