Repository testcontainers/testcontainers-dotnet, pull requests merged in 2023-06, with the labels that each got.

#910 feat: Add UsingHttpMessageHandler(HttpMessageHandler) to HttpWaitStrategy
  src/Testcontainers/Configurations/WaitStrategies/HttpWaitStrategy.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilHttpRequestIsSucceededTest.cs
Labels: enhancement

#911 fix: Add Docker Desktop (for Linux / macOS) authentication provider
  src/Testcontainers/Builders/DockerDesktopEndpointAuthenticationProvider.cs
  src/Testcontainers/Builders/RootlessUnixEndpointAuthenticationProvider.cs
  src/Testcontainers/Builders/TestcontainersEndpointAuthenticationProvider.cs
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  src/Testcontainers/Containers/DockerContainer.cs
  tests/Testcontainers.Tests/Unit/Configurations/DockerEndpointAuthenticationProviderTest.cs
Labels: bug

#912 fix: Prefer indexing instead of Enumerable methods
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  src/Testcontainers/Containers/DockerContainer.cs
  src/Testcontainers/Images/DockerImage.cs
  src/Testcontainers/Images/IgnoreFile.cs
Labels: chore

#918 docs: Add RabbitMQ module documentation incl. an example
  docs/modules/index.md
  docs/modules/rabbitmq.md
  mkdocs.yml
Labels: documentation

#916 docs: Update Testcontainers for Java docs url
  docs/index.md
Labels: documentation

#923 feat: Change access modifier of OracleBuilder.WithUsername(string) to public
  src/Testcontainers.Oracle/OracleBuilder.cs
Labels: enhancement

#913 feat: Add support for copying directories and files to a container
  src/Testcontainers.Kafka/KafkaBuilder.cs
  src/Testcontainers.MariaDb/MariaDbContainer.cs
  src/Testcontainers.MongoDb/MongoDbContainer.cs
  src/Testcontainers.MsSql/MsSqlContainer.cs
  src/Testcontainers.MySql/MySqlContainer.cs
  src/Testcontainers.Oracle/OracleContainer.cs
  src/Testcontainers.PostgreSql/PostgreSqlContainer.cs
  src/Testcontainers.Redis/RedisContainer.cs
  src/Testcontainers.Redpanda/RedpandaBuilder.cs
  src/Testcontainers/Clients/ITestcontainersClient.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Configurations/Unix.cs
  src/Testcontainers/Configurations/UnixFileMode.cs
  src/Testcontainers/Configurations/Volumes/BinaryResourceMapping.cs
  src/Testcontainers/Configurations/Volumes/FileResourceMapping.cs
  src/Testcontainers/Configurations/Volumes/IResourceMapping.cs
  src/Testcontainers/Configurations/Windows.cs
  src/Testcontainers/Containers/DockerContainer.cs
  src/Testcontainers/Containers/IContainer.cs
  src/Testcontainers/Containers/TarOutputMemoryStream.cs
  src/Testcontainers/Images/DockerfileArchive.cs
  tests/Testcontainers.Kafka.Tests/KafkaContainerTest.cs
  tests/Testcontainers.Platform.Linux.Tests/TarOutputMemoryStreamTest.cs
  tests/Testcontainers.Platform.Linux.Tests/Usings.cs
  tests/Testcontainers.Redpanda.Tests/RedpandaContainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/CopyResourceMappingContainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerTest.cs
Labels: enhancement

#927 fix: Ensure site_url is set in the MkDocs config to prevent <loc>None</loc> in sitemap generation
  mkdocs.yml
Labels: bug

#928 chore: Add DebugLogLevelEnabled property to default logger implementation
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Clients/DockerContainerOperations.cs
  src/Testcontainers/Clients/TraceProgress.cs
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  src/Testcontainers/Containers/DockerContainer.cs
  src/Testcontainers/Containers/PortForwarding.cs
  src/Testcontainers/Logger.cs
  src/Testcontainers/Logging.cs
Labels: chore

#930 fix: Use the actual Docker endpoint to extract the socket path for the Resource Reaper
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  src/Testcontainers/Containers/ResourceReaper.cs
Labels: bug

#932 feat: Support coping directories using WithResourceMapping(string, string)
  docs/api/create_docker_container.md
  src/Testcontainers.WebDriver/WebDriverBuilder.cs
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Builders/IContainerBuilder`2.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Configurations/Volumes/BinaryResourceMapping.cs
  src/Testcontainers/Configurations/Volumes/FileResourceMapping.cs
  src/Testcontainers/Configurations/Volumes/IResourceMapping.cs
  tests/Testcontainers.Platform.Linux.Tests/TarOutputMemoryStreamTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/CopyResourceMappingContainerTest.cs
Labels: enhancement, breaking change

#935 docs: Fix typo in Testcontainers properties file path
  docs/custom_configuration/index.md
Labels: documentation

#938 fix: Copy files to container without removing first character from filename
  src/Testcontainers/Containers/TarOutputMemoryStream.cs
Labels: bug

#939 docs: Provide instructions for copying directories or files to the container
  docs/api/create_docker_container.md
Labels: documentation

#942 fix: Replace mysql with mariadb binary in MariaDB module
  src/Testcontainers.MariaDb/MariaDbBuilder.cs
  src/Testcontainers.MariaDb/MariaDbContainer.cs
Labels: bug
