Repository testcontainers/testcontainers-dotnet, pull requests merged in 2023-11, with the labels that each got.

#1038 fix: Prevent invalid negative timestamps getting container logs
  src/Testcontainers/Clients/DockerContainerOperations.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
Labels: bug

#1009 feat: Extend the "wait until file exists" API to distinguish between the test host and container filesystem
  src/Testcontainers/Configurations/FileSystem.cs
  src/Testcontainers/Configurations/WaitStrategies/IWaitForContainerOS.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilFileExistsInContainer.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilFileExistsOnHost.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitForContainerOS.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilFileExistsInContainerTest.cs
Labels: enhancement

#1040 fix: Retain the internal Couchbase builder configuration if the user overrides the default configuration
  src/Testcontainers.Couchbase/CouchbaseBuilder.cs
Labels: bug

#1043 refactor: Cache Docker image full and host name
  docs/modules/index.md
  src/Testcontainers/Images/DockerImage.cs
  tests/Testcontainers.Tests/Unit/Images/TestcontainersImageTest.cs
Labels: chore

#1050 feat: Improve tar stream logging (copy files to container)
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Clients/DockerContainerOperations.cs
  src/Testcontainers/Clients/IDockerContainerOperations.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Configurations/Containers/ContainerConfiguration.cs
  src/Testcontainers/Configurations/Containers/IContainerConfiguration.cs
  src/Testcontainers/Containers/TarOutputMemoryStream.cs
  src/Testcontainers/Logging.cs
  tests/Testcontainers.Platform.Linux.Tests/TarOutputMemoryStreamTest.cs
  tests/Testcontainers.Platform.Linux.Tests/Usings.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/CopyResourceMappingContainerTest.cs
Labels: enhancement

#837 feat: Add JanusGraph module
  Testcontainers.sln
  src/Testcontainers.JanusGraph/.editorconfig
  src/Testcontainers.JanusGraph/JanusGraphBuilder.cs
  src/Testcontainers.JanusGraph/JanusGraphConfiguration.cs
  src/Testcontainers.JanusGraph/JanusGraphContainer.cs
  src/Testcontainers.JanusGraph/Testcontainers.JanusGraph.csproj
  src/Testcontainers.JanusGraph/Usings.cs
  tests/Testcontainers.JanusGraph.Tests/.editorconfig
  tests/Testcontainers.JanusGraph.Tests/JanusGraphContainerTest.cs
  tests/Testcontainers.JanusGraph.Tests/Testcontainers.JanusGraph.Tests.csproj
  tests/Testcontainers.JanusGraph.Tests/Usings.cs
Labels: enhancement

#1034 feat: Add BigQuery module
  Testcontainers.sln
  src/Testcontainers.BigQuery/.editorconfig
  src/Testcontainers.BigQuery/BigQueryBuilder.cs
  src/Testcontainers.BigQuery/BigQueryConfiguration.cs
  src/Testcontainers.BigQuery/BigQueryContainer.cs
  src/Testcontainers.BigQuery/Testcontainers.BigQuery.csproj
  src/Testcontainers.BigQuery/Usings.cs
  tests/Testcontainers.BigQuery.Tests/.editorconfig
  tests/Testcontainers.BigQuery.Tests/BigQueryContainerTest.cs
  tests/Testcontainers.BigQuery.Tests/Testcontainers.BigQuery.Tests.csproj
  tests/Testcontainers.BigQuery.Tests/Usings.cs
Labels: enhancement

#1046 feat: Add Bigtable module
  Testcontainers.sln
  docs/modules/index.md
  src/Testcontainers.Bigtable/.editorconfig
  src/Testcontainers.Bigtable/BigtableBuilder.cs
  src/Testcontainers.Bigtable/BigtableConfiguration.cs
  src/Testcontainers.Bigtable/BigtableContainer.cs
  src/Testcontainers.Bigtable/Testcontainers.Bigtable.csproj
  src/Testcontainers.Bigtable/Usings.cs
  src/Testcontainers.WebDriver/WebDriverConfiguration.cs
  tests/Testcontainers.Bigtable.Tests/.editorconfig
  tests/Testcontainers.Bigtable.Tests/BigtableContainerTest.cs
  tests/Testcontainers.Bigtable.Tests/Testcontainers.Bigtable.Tests.csproj
  tests/Testcontainers.Bigtable.Tests/Usings.cs
  tests/Testcontainers.InfluxDb.Tests/InfluxDbContainerTest.cs
  tests/Testcontainers.LocalStack.Tests/LocalStackContainerTest.cs
  tests/Testcontainers.Platform.Linux.Tests/TarOutputMemoryStreamTest.cs
  tests/Testcontainers.PubSub.Tests/PubSubContainerTest.cs
Labels: enhancement

#1057 chore: Remove Microsoft.SourceLink.GitHub
  src/Templates/CSharp/Testcontainers.ModuleName/Testcontainers.ModuleName.csproj
  src/Testcontainers.Azurite/Testcontainers.Azurite.csproj
  src/Testcontainers.BigQuery/Testcontainers.BigQuery.csproj
  src/Testcontainers.Bigtable/Testcontainers.Bigtable.csproj
  src/Testcontainers.ClickHouse/Testcontainers.ClickHouse.csproj
  src/Testcontainers.Consul/Testcontainers.Consul.csproj
  src/Testcontainers.CosmosDb/Testcontainers.CosmosDb.csproj
  src/Testcontainers.CouchDb/Testcontainers.CouchDb.csproj
  src/Testcontainers.Couchbase/Testcontainers.Couchbase.csproj
  src/Testcontainers.DynamoDb/Testcontainers.DynamoDb.csproj
  src/Testcontainers.Elasticsearch/Testcontainers.Elasticsearch.csproj
  src/Testcontainers.EventStoreDb/Testcontainers.EventStoreDb.csproj
  src/Testcontainers.FakeGcsServer/Testcontainers.FakeGcsServer.csproj
  src/Testcontainers.Firestore/Testcontainers.Firestore.csproj
  src/Testcontainers.InfluxDb/Testcontainers.InfluxDb.csproj
  src/Testcontainers.JanusGraph/Testcontainers.JanusGraph.csproj
  src/Testcontainers.K3s/Testcontainers.K3s.csproj
  src/Testcontainers.Kafka/Testcontainers.Kafka.csproj
  src/Testcontainers.Keycloak/Testcontainers.Keycloak.csproj
  src/Testcontainers.Kusto/Testcontainers.Kusto.csproj
  src/Testcontainers.LocalStack/Testcontainers.LocalStack.csproj
  src/Testcontainers.MariaDb/Testcontainers.MariaDb.csproj
  src/Testcontainers.Minio/Testcontainers.Minio.csproj
  src/Testcontainers.MongoDb/Testcontainers.MongoDb.csproj
  src/Testcontainers.MsSql/Testcontainers.MsSql.csproj
  src/Testcontainers.MySql/Testcontainers.MySql.csproj
  src/Testcontainers.Nats/Testcontainers.Nats.csproj
  src/Testcontainers.Neo4j/Testcontainers.Neo4j.csproj
  src/Testcontainers.Oracle/Testcontainers.Oracle.csproj
  src/Testcontainers.Papercut/Testcontainers.Papercut.csproj
  src/Testcontainers.PostgreSql/Testcontainers.PostgreSql.csproj
  src/Testcontainers.PubSub/Testcontainers.PubSub.csproj
  src/Testcontainers.RabbitMq/Testcontainers.RabbitMq.csproj
  src/Testcontainers.RavenDb/Testcontainers.RavenDb.csproj
  src/Testcontainers.Redis/Testcontainers.Redis.csproj
  src/Testcontainers.Redpanda/Testcontainers.Redpanda.csproj
  src/Testcontainers.SqlEdge/Testcontainers.SqlEdge.csproj
  src/Testcontainers.WebDriver/Testcontainers.WebDriver.csproj
  src/Testcontainers/Testcontainers.csproj
Labels: chore

#1055 feat: Add ActiveMQ Artemis module
  Testcontainers.sln
  src/Testcontainers.ActiveMq/.editorconfig
  src/Testcontainers.ActiveMq/ActiveMqConfiguration.cs
  src/Testcontainers.ActiveMq/ArtemisBuilder.cs
  src/Testcontainers.ActiveMq/ArtemisContainer.cs
  src/Testcontainers.ActiveMq/Testcontainers.ActiveMq.csproj
  src/Testcontainers.ActiveMq/Usings.cs
  tests/Testcontainers.ActiveMq.Tests/.editorconfig
  tests/Testcontainers.ActiveMq.Tests/ArtemisContainerTest.cs
  tests/Testcontainers.ActiveMq.Tests/Testcontainers.ActiveMq.Tests.csproj
  tests/Testcontainers.ActiveMq.Tests/Usings.cs
Labels: enhancement
