Repository testcontainers/testcontainers-dotnet, pull requests merged in 2023-05, with the labels that each got.

#881 fix: Remove trailing slash from rootless Docker socket path
  Directory.Build.props
  src/Testcontainers/Builders/RootlessUnixEndpointAuthenticationProvider.cs
Labels: bug

#883 fix: Replace CLI command to detect open ports in Linux containers
  src/Testcontainers/Configurations/WaitStrategies/UntilUnixPortIsAvailable.cs
Labels: bug

#882 feat: Add Docker image build policy
  src/Testcontainers/Builders/IImageFromDockerfileBuilder`1.cs
  src/Testcontainers/Builders/ImageFromDockerfileBuilder.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Configurations/Images/IImageFromDockerfileConfiguration.cs
  src/Testcontainers/Configurations/Images/ImageFromDockerfileConfiguration.cs
  tests/Testcontainers.Tests/Assets/Dockerfile
  tests/Testcontainers.Tests/Assets/healthWaitStrategy/Dockerfile
  tests/Testcontainers.Tests/Fixtures/Images/HealthCheckFixture.cs
Labels: enhancement

#884 chore: Build image with ITestcontainersClient implementation
  src/Testcontainers/Clients/DockerVolumeOperations.cs
  src/Testcontainers/Clients/ITestcontainersClient.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Containers/ResourceReaper.cs
  src/Testcontainers/Images/FutureDockerImage.cs
  src/Testcontainers/Networks/DockerNetwork.cs
  src/Testcontainers/Volumes/DockerVolume.cs
  tests/Testcontainers.Tests/Unit/Configurations/ResourcePropertiesTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/TestcontainersAccessInformationTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilContainerIsHealthyTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilHttpRequestIsSucceededTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/CopyResourceMappingContainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/GetContainerLogsTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/ProtectDockerDaemonSocketTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/ReadFileFromContainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerCancellationTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerTest.cs
  tests/Testcontainers.Tests/Unit/Networks/TestcontainerNetworkBuilderTest.cs
  tests/Testcontainers.Tests/Unit/Volumes/TestcontainersVolumeBuilderTest.cs
Labels: chore

#888 docs: Add Docker remote host configuration
  docs/custom_configuration/index.md
Labels: documentation

#880 feat: Add Keycloak module
  Testcontainers.sln
  src/Testcontainers.Keycloak/.editorconfig
  src/Testcontainers.Keycloak/KeycloakBuilder.cs
  src/Testcontainers.Keycloak/KeycloakConfiguration.cs
  src/Testcontainers.Keycloak/KeycloakContainer.cs
  src/Testcontainers.Keycloak/Testcontainers.Keycloak.csproj
  src/Testcontainers.Keycloak/Usings.cs
  tests/Testcontainers.Keycloak.Tests/.editorconfig
  tests/Testcontainers.Keycloak.Tests/KeycloakContainerTest.cs
  tests/Testcontainers.Keycloak.Tests/Testcontainers.Keycloak.Tests.csproj
  tests/Testcontainers.Keycloak.Tests/Usings.cs
Labels: enhancement

#885 feat: Add TC host strategy
  src/Testcontainers.Keycloak/KeycloakContainer.cs
  src/Testcontainers/Builders/TestcontainersCloudEndpointAuthenticationProvider.cs
  src/Testcontainers/Configurations/CustomConfiguration.cs
  src/Testcontainers/Configurations/EnvironmentConfiguration.cs
  src/Testcontainers/Configurations/PropertiesFileConfiguration.cs
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  tests/Testcontainers.Tests/Fixtures/Images/HealthCheckFixture.cs
  tests/Testcontainers.Tests/Unit/Configurations/DockerEndpointAuthenticationProviderTest.cs
Labels: enhancement

#895 docs: Add information about running Testcontainers in specific CI environments
  docs/api/create_docker_image.md
  docs/cicd/index.md
  docs/index.md
  mkdocs.yml
Labels: documentation

#896 chore: Update Ryuk image from version 0.4.0 to 0.5.1
  docs/api/resource-reaper.md
  docs/cicd/index.md
  docs/custom_configuration/index.md
  docs/index.md
  src/Testcontainers/Containers/ResourceReaper.cs
  tests/Testcontainers.Commons/CommonImages.cs
Labels: chore

#898 chore: Update Docker.DotNet from version 3.125.13 to 3.125.15
  Packages.props
Labels: chore

#899 chore: Favor custom environment variable configurations over properties file
  src/Testcontainers/Builders/DockerRegistryAuthenticationProvider.cs
  src/Testcontainers/Builders/EnvironmentEndpointAuthenticationProvider.cs
  src/Testcontainers/Builders/MTlsEndpointAuthenticationProvider.cs
  src/Testcontainers/Builders/TlsEndpointAuthenticationProvider.cs
  src/Testcontainers/Configurations/TestcontainersSettings.cs
Labels: chore

#900 fix: Do not create a Port Forwarding Container instance if auto-discovery does not detect Docker host
  Directory.Build.props
  src/Testcontainers/Containers/PortForwarding.cs
Labels: bug

#901 chore: Refactor legacy TestcontainersContainerTest class
  Directory.Build.props
  tests/Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerTest.cs
Labels: chore

#904 chore: Update WeatherForecast example
  examples/WeatherForecast/Packages.props
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastContainer.cs
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastImage.cs
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastTest.cs
Labels: chore
