Repository testcontainers/testcontainers-dotnet, pull requests merged in 2023-08, with the labels that each got.

#966 chore: Add test coverage to unbound port bindings
  tests/Testcontainers.Platform.Linux.Tests/TarOutputMemoryStreamTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerTest.cs
Labels: chore

#971 chore: Remove `CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT` env var
  src/Testcontainers.ClickHouse/ClickHouseBuilder.cs
Labels: chore

#970 chore: Add User-Agent HTTP header to Docker.DotNet client
  src/Testcontainers/Clients/DefaultLabels.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Configurations/AuthConfigs/DockerEndpointAuthenticationConfiguration.cs
Labels: chore

#979 fix: Do not pre pull Dockerfile build stages that do not correspond to base images
  .devcontainer/devcontainer.json
  src/Testcontainers/Clients/DockerImageOperations.cs
  src/Testcontainers/Clients/IDockerImageOperations.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Configurations/WaitStrategies/IWaitForContainerOS.cs
  src/Testcontainers/Images/DockerfileArchive.cs
  tests/Testcontainers.Tests/Assets/.dockerignore
  tests/Testcontainers.Tests/Assets/pullBaseImages/Dockerfile
  tests/Testcontainers.Tests/Unit/Images/ImageFromDockerfileTest.cs
Labels: bug

#967 docs: Add global Testcontainers header
  docs/css/extra.css
  docs/css/tc-header.css
  docs/index.md
  docs/js/tc-header.js
  docs/language-logos/ruby.svg
  docs/testcontainers-logo.svg
  docs/theme/main.html
  docs/theme/partials/header.html
  docs/theme/partials/nav.html
  docs/theme/partials/tc-header.html
  mkdocs.yml
Labels: documentation
