Repository testcontainers/testcontainers-dotnet, pull requests merged in 2023-12, with the labels that each got.

#1061 docs: Add ASP.NET integration test example
  docs/examples/aspnet.md
Labels: documentation

#1058 feat: Add ArangoDB module
  Testcontainers.sln
  src/Testcontainers.ArangoDb/.editorconfig
  src/Testcontainers.ArangoDb/ArangoDbBuilder.cs
  src/Testcontainers.ArangoDb/ArangoDbConfiguration.cs
  src/Testcontainers.ArangoDb/ArangoDbContainer.cs
  src/Testcontainers.ArangoDb/Testcontainers.ArangoDb.csproj
  src/Testcontainers.ArangoDb/Usings.cs
  tests/Testcontainers.ArangoDb.Tests/.editorconfig
  tests/Testcontainers.ArangoDb.Tests/ArangoDbContainerTest.cs
  tests/Testcontainers.ArangoDb.Tests/Testcontainers.ArangoDb.Tests.csproj
  tests/Testcontainers.ArangoDb.Tests/Usings.cs
Labels: enhancement

#1059 chore: Replace custom wait strategy with default strategies
  src/Testcontainers.K3s/K3sBuilder.cs
  src/Testcontainers.Oracle/OracleBuilder.cs
  src/Testcontainers.RabbitMq/RabbitMqBuilder.cs
  src/Testcontainers.RavenDb/RavenDbBuilder.cs
  src/Testcontainers.Redis/RedisBuilder.cs
  src/Testcontainers.SqlEdge/SqlEdgeBuilder.cs
Labels: chore

#1064 fix: Retry configuring Couchbase on HttpIOException
  src/Testcontainers.Couchbase/CouchbaseBuilder.cs
Labels: bug

#1079 chore: Invert #if NETSTANDARD* conditional compilation conditions
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Containers/ResourceReaper.cs
  src/Testcontainers/Containers/TarOutputMemoryStream.cs
  src/Testcontainers/Images/IgnoreFile.cs
Labels: chore
