Repository testcontainers/testcontainers-dotnet, pull requests merged in 2023-10, with the labels that each got.

#1008 docs: Add Microsoft SQL Server example
  docs/modules/microsoft-sql-server.md
Labels: documentation

#1010 docs: Add Elasticsearch example
  docs/modules/elasticsearch.md
Labels: documentation

#1012 docs: Add MongoDB example
  docs/modules/mongodb.md
Labels: documentation

#1016 feat: Ignore FROM args when pre-pulling images
  docs/modules/elasticsearch.md
  docs/modules/mongodb.md
  docs/modules/mssql.md
  docs/modules/neo4j.md
  mkdocs.yml
  src/Testcontainers/Images/DockerfileArchive.cs
  tests/Testcontainers.Neo4j.Tests/Neo4jContainerTest.cs
  tests/Testcontainers.Tests/Assets/pullBaseImages/Dockerfile
  tests/Testcontainers.Tests/Unit/Images/ImageFromDockerfileTest.cs
Labels: enhancement

#1018 feat: Use Docker's inspect API to get resource information
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Builders/IContainerBuilder`2.cs
  src/Testcontainers/Builders/IImageFromDockerfileBuilder`1.cs
  src/Testcontainers/Builders/ImageFromDockerfileBuilder.cs
  src/Testcontainers/Clients/DockerContainerOperations.cs
  src/Testcontainers/Clients/DockerImageOperations.cs
  src/Testcontainers/Clients/DockerNetworkOperations.cs
  src/Testcontainers/Clients/DockerVolumeOperations.cs
  src/Testcontainers/Clients/IDockerContainerOperations.cs
  src/Testcontainers/Clients/IDockerImageOperations.cs
  src/Testcontainers/Clients/IDockerNetworkOperations.cs
  src/Testcontainers/Clients/IDockerVolumeOperations.cs
  src/Testcontainers/Clients/IHasListOperations.cs
  src/Testcontainers/Clients/ITestcontainersClient.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Configurations/Containers/ContainerConfiguration.cs
  src/Testcontainers/Configurations/Containers/IContainerConfiguration.cs
  src/Testcontainers/Configurations/Images/IImageFromDockerfileConfiguration.cs
  src/Testcontainers/Configurations/Images/ImageFromDockerfileConfiguration.cs
  src/Testcontainers/Containers/DockerContainer.cs
  src/Testcontainers/Images/FutureDockerImage.cs
  src/Testcontainers/Images/PullPolicy.cs
  src/Testcontainers/Volumes/DockerVolume.cs
Labels: enhancement, breaking change

#1020 chore: Remove unnecessary internal APIs
  src/Testcontainers/Clients/ContainerConfigurationConverter.cs
  src/Testcontainers/Clients/DockerContainerOperations.cs
  src/Testcontainers/Clients/DockerImageOperations.cs
  src/Testcontainers/Clients/DockerNetworkOperations.cs
  src/Testcontainers/Clients/DockerSystemOperations.cs
  src/Testcontainers/Clients/DockerVolumeOperations.cs
  src/Testcontainers/Clients/IHasListOperations.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Images/FutureDockerImage.cs
  src/Testcontainers/Images/MatchImage.cs
  tests/Testcontainers.Tests/Unit/Configurations/ResourcePropertiesTest.cs
  tests/Testcontainers.Tests/Unit/Networks/TestcontainerNetworkBuilderTest.cs
  tests/Testcontainers.Tests/Unit/Volumes/TestcontainersVolumeBuilderTest.cs
Labels: chore

#920 feat: Share common interface (IDatabaseContainer) for ADO.NET compatible containers
  Testcontainers.sln
  src/Testcontainers.ClickHouse/ClickHouseContainer.cs
  src/Testcontainers.MariaDb/MariaDbContainer.cs
  src/Testcontainers.MsSql/MsSqlContainer.cs
  src/Testcontainers.MySql/MySqlContainer.cs
  src/Testcontainers.Oracle/OracleContainer.cs
  src/Testcontainers.PostgreSql/PostgreSqlContainer.cs
  src/Testcontainers.SqlEdge/SqlEdgeContainer.cs
  src/Testcontainers/Containers/IDatabaseContainer.cs
  tests/Testcontainers.Databases.Tests/.editorconfig
  tests/Testcontainers.Databases.Tests/DatabasesContainerTest.cs
  tests/Testcontainers.Databases.Tests/Testcontainers.Databases.Tests.csproj
  tests/Testcontainers.Databases.Tests/Usings.cs
Labels: enhancement

#1005 feat: Add PubSub module
  Testcontainers.sln
  src/Testcontainers.PubSub/.editorconfig
  src/Testcontainers.PubSub/PubSubBuilder.cs
  src/Testcontainers.PubSub/PubSubConfiguration.cs
  src/Testcontainers.PubSub/PubSubContainer.cs
  src/Testcontainers.PubSub/Testcontainers.PubSub.csproj
  src/Testcontainers.PubSub/Usings.cs
  tests/Testcontainers.PubSub.Tests/.editorconfig
  tests/Testcontainers.PubSub.Tests/PubSubContainerTests.cs
  tests/Testcontainers.PubSub.Tests/Testcontainers.PubSub.Tests.csproj
  tests/Testcontainers.PubSub.Tests/Usings.cs
Labels: enhancement

#1023 feat: Add Google Cloud Storage API (fake-gcs-server) module
  Testcontainers.sln
  src/Testcontainers.FakeGcsServer/.editorconfig
  src/Testcontainers.FakeGcsServer/FakeGcsServerBuilder.cs
  src/Testcontainers.FakeGcsServer/FakeGcsServerConfiguration.cs
  src/Testcontainers.FakeGcsServer/FakeGcsServerContainer.cs
  src/Testcontainers.FakeGcsServer/Testcontainers.FakeGcsServer.csproj
  src/Testcontainers.FakeGcsServer/Usings.cs
  tests/Testcontainers.FakeGcsServer.Tests/.editorconfig
  tests/Testcontainers.FakeGcsServer.Tests/FakeGcsServerContainerTest.cs
  tests/Testcontainers.FakeGcsServer.Tests/Testcontainers.FakeGcsServer.Tests.csproj
  tests/Testcontainers.FakeGcsServer.Tests/Usings.cs
Labels: enhancement

#1028 feat: Add Consul module
  Testcontainers.sln
  src/Testcontainers.Consul/.editorconfig
  src/Testcontainers.Consul/ConsulBuilder.cs
  src/Testcontainers.Consul/ConsulConfiguration.cs
  src/Testcontainers.Consul/ConsulContainer.cs
  src/Testcontainers.Consul/Testcontainers.Consul.csproj
  src/Testcontainers.Consul/Usings.cs
  tests/Testcontainers.Consul.Tests/.editorconfig
  tests/Testcontainers.Consul.Tests/ConsulContainerTest.cs
  tests/Testcontainers.Consul.Tests/Testcontainers.Consul.Tests.csproj
  tests/Testcontainers.Consul.Tests/Usings.cs
Labels: enhancement

#1032 chore: Do not pre-pull cached images
  src/Testcontainers.FakeGcsServer/FakeGcsServerBuilder.cs
  src/Testcontainers/Clients/FilterByProperty.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  tests/Testcontainers.Tests/Assets/pullBaseImages/Dockerfile
  tests/Testcontainers.Tests/Unit/Images/ImageFromDockerfileTest.cs
Labels: enhancement
