Repository testcontainers/testcontainers-dotnet, pull requests merged in 2023-07, with the labels that each got.

#945 chore: Disable Elasticsearch GeoIP2 downloads
  .github/workflows/cicd.yml
  src/Testcontainers.Elasticsearch/ElasticsearchBuilder.cs
Labels: enhancement

#947 chore: Bump Azurite from 3.23.0 to 3.24.0
  docs/modules/index.md
  src/Testcontainers.Azurite/AzuriteBuilder.cs
  tests/Testcontainers.Azurite.Tests/Testcontainers.Azurite.Tests.csproj
Labels: chore

#958 fix: Do not dispose a custom HTTP message handler in an HTTP wait strategy
  src/Testcontainers/Configurations/WaitStrategies/HttpWaitStrategy.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilHttpRequestIsSucceededTest.cs
Labels: bug

#961 fix(CosmosDb): Wait until all partitions are started
  src/Testcontainers.CosmosDb/CosmosDbBuilder.cs
Labels: bug

#959 feat: Restore output consumer support
  docs/api/create_docker_container.md
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Clients/ITestcontainersClient.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Configurations/WaitStrategies/IWaitForContainerOS.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitForContainerOS.cs
  src/Testcontainers/Containers/DockerContainer.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilHttpRequestIsSucceededTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerTest.cs
Labels: enhancement
