Repository testcontainers/testcontainers-dotnet, pull requests merged in 2023-01, with the labels that each got.

#726 feat(#725): Do not return JSON auth config for partial Docker registry matches
  src/Testcontainers/Builders/Base64Provider.cs
  src/Testcontainers/Builders/CredsHelperProvider.cs
  tests/Testcontainers.Tests/Unit/Configurations/DockerRegistryAuthenticationProviderTest.cs
Labels: enhancement

#727 chore: Replace host port 0 with an empty string
  src/Testcontainers/Builders/TestcontainersBuilder.cs
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilHttpRequestIsSucceededTest.cs
Labels: chore

#731 docs: Add Docker Desktop Compose example
  docs/examples/compose.md
  mkdocs.yml
Labels: documentation

#738 fix: Wait until LocalStack writes ready message
  src/Testcontainers/Configurations/Modules/MessageBrokers/LocalStackTestcontainerConfiguration.cs
  src/Testcontainers/Configurations/TestcontainersSettings.cs
Labels: bug

#735 feat: Add GitHub Codespaces configuration (Dev Container)
  .devcontainer/devcontainer.json
  .github/workflows/cicd.yml
  Directory.Build.props
  Packages.props
  build.cake
  examples/WeatherForecast/Directory.Build.props
  examples/WeatherForecast/Packages.props
  examples/WeatherForecast/src/WeatherForecast/Pages/SevenDayWeatherForecast.razor
  examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecast.InProcess.Tests.csproj
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecast.Tests.csproj
  src/Testcontainers/Testcontainers.csproj
  tests/Testcontainers.Commons/Testcontainers.Commons.csproj
  tests/Testcontainers.Platform.Linux.Tests/Testcontainers.Platform.Linux.Tests.csproj
  tests/Testcontainers.Platform.Windows.Tests/Testcontainers.Platform.Windows.Tests.csproj
  tests/Testcontainers.ResourceReaper.Tests/Testcontainers.ResourceReaper.Tests.csproj
  tests/Testcontainers.Tests/Testcontainers.Tests.csproj
Labels: enhancement

#739 chore: Add link Open in GitHub Codespaces
  README.md
Labels: documentation

#743 feat(#493): Add container lifecycle events
  requirements.txt
  src/Testcontainers/Builders/AbstractBuilder`2.cs
  src/Testcontainers/Clients/ITestcontainersClient.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Configurations/WaitStrategies/HttpWaitStrategy.cs
  src/Testcontainers/Configurations/WaitStrategies/IWaitUntil.cs
  src/Testcontainers/Configurations/WaitStrategies/IWaitWhile.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilContainerIsHealthy.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilContainerIsRunning.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilFilesExists.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilMessageIsLogged.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilOperationIsSucceeded.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilUnixCommandIsCompleted.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitStrategy.cs
  src/Testcontainers/Containers/DockerContainer.cs
  src/Testcontainers/Containers/IContainer.cs
  src/Testcontainers/Guard.Argument.cs
  src/Testcontainers/Guard.Null.cs
  src/Testcontainers/Guard.String.cs
  src/Testcontainers/Resource.cs
  src/Testcontainers/_OBSOLETE_/Modules/MessageBrokers/LocalStackTestcontainerConfiguration.cs
  tests/Testcontainers.Tests/Fixtures/Configurations/WaitUntilFiveSecondsPassedFixture.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/ProtectDockerDaemonSocket.cs
  tests/Testcontainers.Tests/Unit/Configurations/TestcontainersAccessInformationTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/TestcontainersWaitStrategyTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilHttpRequestIsSucceededTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilMessageIsLoggedTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilOperationIsSucceededTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerTest.cs
  tests/Testcontainers.Tests/Unit/GuardTest.cs
  tests/Testcontainers.Tests/Unit/Images/TestcontainersImageTest.cs
Labels: enhancement, breaking change

#742 feat(#493): Add .NET module template
  Directory.Build.props
  LICENSE
  README.md
  docs/index.md
  src/Templates/CSharp/.template.config/template.json
  src/Templates/CSharp/Testcontainers.ModuleName/ModuleNameBuilder.cs
  src/Templates/CSharp/Testcontainers.ModuleName/ModuleNameConfiguration.cs
  src/Templates/CSharp/Testcontainers.ModuleName/ModuleNameContainer.cs
  src/Templates/CSharp/Testcontainers.ModuleName/Testcontainers.ModuleName.csproj
  src/Templates/CSharp/Testcontainers.ModuleName/Usings.cs
  src/Templates/FSharp/.gitkeep
  src/Templates/README.md
  src/Templates/VisualBasic/.gitkeep
  src/Testcontainers/Builders/AbstractBuilder`4.cs
  src/Testcontainers/Builders/BuildConfiguration.cs
  src/Testcontainers/Builders/ContainerBuilder.cs
  src/Testcontainers/Builders/IAbstractBuilder`3.cs
Labels: enhancement

#744 feat(#493): Prepare module NuGet support, sign NuGet
  .cake-scripts/credentials.cake
  .cake-scripts/version.cake
  .config/dotnet-tools.json
  .github/workflows/cicd.yml
  Testcontainers.sln
  build.cake
  tests/Testcontainers.Commons/Testcontainers.Commons.csproj
Labels: chore

#746 feat: Invoke create parameter modifier for image, network, volume build or create
  src/Testcontainers/Builders/ImageFromDockerfileBuilder.cs
  src/Testcontainers/Clients/DockerImageOperations.cs
  src/Testcontainers/Clients/DockerNetworkOperations.cs
  src/Testcontainers/Clients/DockerVolumeOperations.cs
  src/Testcontainers/Configurations/Images/IImageFromDockerfileConfiguration.cs
  src/Testcontainers/Configurations/Images/ImageFromDockerfileConfiguration.cs
  tests/Testcontainers.Tests/Unit/Configurations/TestcontainersAccessInformationTest.cs
  tests/Testcontainers.Tests/Unit/Images/ImageFromDockerfileTest.cs
  tests/Testcontainers.Tests/Unit/Networks/TestcontainerNetworkBuilderTest.cs
  tests/Testcontainers.Tests/Unit/Volumes/TestcontainersVolumeBuilderTest.cs
Labels: enhancement
