Repository testcontainers/testcontainers-dotnet, pull requests merged in 2023-09, with the labels that each got.

#987 chore: Improve error message when Docker is not running
  src/Testcontainers/Builders/AbstractBuilder`4.cs
Labels: chore

#991 docs: Add documentation on enabling debug log messages for the default logger
  docs/custom_configuration/index.md
Labels: documentation

#983 feat: Allow MongoDb module configuration without credentials
  src/Testcontainers.MongoDb/MongoDbBuilder.cs
  tests/Testcontainers.MongoDb.Tests/MongoDbContainerTest.cs
Labels: enhancement

#997 feat: Prepare next release cycle (3.6.0)
  Directory.Build.props
  Packages.props
  docs/modules/index.md
  examples/WeatherForecast/Packages.props
  examples/WeatherForecast/src/WeatherForecast/Pages/SevenDayWeatherForecast.razor
  examples/WeatherForecast/src/WeatherForecast/Pages/_Host.cshtml
  examples/WeatherForecast/src/WeatherForecast/Pages/_Layout.cshtml
  src/Testcontainers/Clients/TestcontainersClient.cs
  tests/Testcontainers.Azurite.Tests/Testcontainers.Azurite.Tests.csproj
  tests/Testcontainers.ClickHouse.Tests/Testcontainers.ClickHouse.Tests.csproj
  tests/Testcontainers.CosmosDb.Tests/Testcontainers.CosmosDb.Tests.csproj
  tests/Testcontainers.CouchDb.Tests/Testcontainers.CouchDb.Tests.csproj
  tests/Testcontainers.Couchbase.Tests/Testcontainers.Couchbase.Tests.csproj
  tests/Testcontainers.DynamoDb.Tests/Testcontainers.DynamoDb.Tests.csproj
  tests/Testcontainers.Elasticsearch.Tests/Testcontainers.Elasticsearch.Tests.csproj
  tests/Testcontainers.EventStoreDb.Tests/Testcontainers.EventStoreDb.Tests.csproj
  tests/Testcontainers.InfluxDb.Tests/Testcontainers.InfluxDb.Tests.csproj
  tests/Testcontainers.K3s.Tests/Testcontainers.K3s.Tests.csproj
  tests/Testcontainers.Kafka.Tests/Testcontainers.Kafka.Tests.csproj
  tests/Testcontainers.Keycloak.Tests/Testcontainers.Keycloak.Tests.csproj
  tests/Testcontainers.Kusto.Tests/Testcontainers.Kusto.Tests.csproj
  tests/Testcontainers.LocalStack.Tests/Testcontainers.LocalStack.Tests.csproj
  tests/Testcontainers.MariaDb.Tests/Testcontainers.MariaDb.Tests.csproj
  tests/Testcontainers.Minio.Tests/Testcontainers.Minio.Tests.csproj
  tests/Testcontainers.MongoDb.Tests/Testcontainers.MongoDb.Tests.csproj
  tests/Testcontainers.MsSql.Tests/Testcontainers.MsSql.Tests.csproj
  tests/Testcontainers.MySql.Tests/Testcontainers.MySql.Tests.csproj
  tests/Testcontainers.Neo4j.Tests/Testcontainers.Neo4j.Tests.csproj
  tests/Testcontainers.Oracle.Tests/Testcontainers.Oracle.Tests.csproj
  tests/Testcontainers.Platform.Linux.Tests/DependsOnTest.cs
  tests/Testcontainers.Platform.Linux.Tests/Testcontainers.Platform.Linux.Tests.csproj
  tests/Testcontainers.Platform.Windows.Tests/Testcontainers.Platform.Windows.Tests.csproj
  tests/Testcontainers.PostgreSql.Tests/Testcontainers.PostgreSql.Tests.csproj
  tests/Testcontainers.RabbitMq.Tests/Testcontainers.RabbitMq.Tests.csproj
  tests/Testcontainers.RavenDb.Tests/Testcontainers.RavenDb.Tests.csproj
  tests/Testcontainers.Redis.Tests/Testcontainers.Redis.Tests.csproj
  tests/Testcontainers.Redpanda.Tests/Testcontainers.Redpanda.Tests.csproj
  tests/Testcontainers.SqlEdge.Tests/Testcontainers.SqlEdge.Tests.csproj
  tests/Testcontainers.WebDriver.Tests/Testcontainers.WebDriver.Tests.csproj
Labels: enhancement

#1002 docs: Add Flyway example
  .config/dotnet-tools.json
  .github/workflows/cicd.yml
  build.cake
  examples/Flyway/.editorconfig
  examples/Flyway/.gitattributes
  examples/Flyway/Directory.Build.props
  examples/Flyway/Flyway.sln
  examples/Flyway/Packages.props
  examples/Flyway/README.md
  examples/Flyway/src/.gitkeep
  examples/Flyway/tests/Flyway.Tests/DbFixture.cs
  examples/Flyway/tests/Flyway.Tests/Flyway.Tests.csproj
  examples/Flyway/tests/Flyway.Tests/FlywayTest.cs
  examples/Flyway/tests/Flyway.Tests/Usings.cs
  examples/Flyway/tests/Flyway.Tests/migrate/V1.0__create_users_table.sql
  examples/Flyway/tests/Flyway.Tests/migrate/V1.1__alter_users_table.sql
  examples/Flyway/tests/Flyway.Tests/migrate/V2.0__seed_example_users.sql
  tests/Testcontainers.PostgreSql.Tests/Testcontainers.PostgreSql.Tests.csproj
Labels: documentation

#988 feat: Add Firestore module
  Testcontainers.sln
  docs/modules/index.md
  src/Testcontainers.Firestore/.editorconfig
  src/Testcontainers.Firestore/FirestoreBuilder.cs
  src/Testcontainers.Firestore/FirestoreConfiguration.cs
  src/Testcontainers.Firestore/FirestoreContainer.cs
  src/Testcontainers.Firestore/Testcontainers.Firestore.csproj
  src/Testcontainers.Firestore/Usings.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  tests/Testcontainers.Firestore.Tests/.editorconfig
  tests/Testcontainers.Firestore.Tests/FirestoreContainerTest.cs
  tests/Testcontainers.Firestore.Tests/Testcontainers.Firestore.Tests.csproj
  tests/Testcontainers.Firestore.Tests/Usings.cs
Labels: enhancement

#1003 feat: Add NATS module
  Testcontainers.sln
  docs/modules/index.md
  src/Testcontainers.MongoDb/MongoDbBuilder.cs
  src/Testcontainers.Nats/.editorconfig
  src/Testcontainers.Nats/NatsBuilder.cs
  src/Testcontainers.Nats/NatsConfiguration.cs
  src/Testcontainers.Nats/NatsContainer.cs
  src/Testcontainers.Nats/Testcontainers.Nats.csproj
  src/Testcontainers.Nats/Usings.cs
  tests/Testcontainers.Nats.Tests/.editorconfig
  tests/Testcontainers.Nats.Tests/NatsContainerTest.cs
  tests/Testcontainers.Nats.Tests/Testcontainers.Nats.Tests.csproj
  tests/Testcontainers.Nats.Tests/Usings.cs
Labels: enhancement
