Repository testcontainers/testcontainers-dotnet, pull requests merged in 2023-02, with the labels that each got.

#748 chore: Rename release branch to main
  .cake-scripts/version.cake
  .github/settings.yml
  .github/workflows/cicd.yml
  .github/workflows/codeql-analysis.yml
  README.md
  docs/index.md
  src/Templates/CSharp/Testcontainers.ModuleName/.editorconfig
  src/Templates/CSharp/Testcontainers.ModuleName/ModuleNameConfiguration.cs
  src/Templates/CSharp/Testcontainers.ModuleName/ModuleNameContainer.cs
  src/Testcontainers.PostgreSql/Usings.cs
  src/Testcontainers/Builders/IAbstractBuilder`3.cs
Labels: chore

#753 chore: Remove obsolete property IDockerNetwork.Id
  src/Testcontainers/BackwardCompatibility/BackwardsCompatibility.cs
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Builders/IContainerBuilder`2.cs
  src/Testcontainers/Networks/DockerNetwork.cs
  tests/Testcontainers.Tests/Unit/Configurations/TestcontainersAccessInformationTest.cs
  tests/Testcontainers.Tests/Unit/Networks/TestcontainerNetworkBuilderTest.cs
  tests/Testcontainers.Tests/Unit/Networks/TestcontainersNetworkTest.cs
  tests/Testcontainers.Tests/Unit/Volumes/TestcontainersVolumeBuilderTest.cs
Labels: chore

#754 chore: Update the WeatherForecast example to 2.4.0
  examples/WeatherForecast/Packages.props
  examples/WeatherForecast/src/WeatherForecast/DatabaseContainer.cs
  examples/WeatherForecast/src/WeatherForecast/DatabaseContainerConfiguration.cs
  examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecastTest.cs
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastContainer.cs
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastImage.cs
Labels: chore

#756 docs: Replace obsolete builders
  docs/api/create_docker_container.md
  docs/api/create_docker_image.md
  docs/api/create_docker_network.md
  docs/api/resource-reaper.md
  docs/api/wait_strategies.md
  docs/examples/aspnet.md
  docs/modules/index.md
  docs/modules/postgres.md
Labels: documentation

#758 fix: Move MsSqlContainerTest class to namespace
  .github/dependabot.yml
  build.cake
  src/Testcontainers.MsSql/MsSqlContainer.cs
  tests/Testcontainers.MsSql.Tests/MsSqlContainerTest.cs
Labels: chore

#759 fix: Use sqlcmd utility to detect readiness of the container
  src/Testcontainers.MsSql/MsSqlBuilder.cs
  src/Testcontainers.MsSql/MsSqlContainer.cs
Labels: chore

#764 feat: Replace Redis module
  Packages.props
  Testcontainers.sln
  src/Testcontainers.MariaDb/MariaDbBuilder.cs
  src/Testcontainers.MySql/MySqlBuilder.cs
  src/Testcontainers.Redis/.editorconfig
  src/Testcontainers.Redis/RedisBuilder.cs
  src/Testcontainers.Redis/RedisConfiguration.cs
  src/Testcontainers.Redis/RedisContainer.cs
  src/Testcontainers.Redis/Testcontainers.Redis.csproj
  src/Testcontainers.Redis/Usings.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/MariaDbTestcontainer.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/MariaDbTestcontainerConfiguration.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/RedisTestcontainer.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/RedisTestcontainerConfiguration.cs
  tests/Testcontainers.Redis.Tests/.editorconfig
  tests/Testcontainers.Redis.Tests/RedisContainerTest.cs
  tests/Testcontainers.Redis.Tests/Testcontainers.Redis.Tests.csproj
  tests/Testcontainers.Redis.Tests/Usings.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/Modules/Databases/MariaDbFixture.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/Modules/Databases/RedisFixture.cs
  tests/Testcontainers.Tests/Testcontainers.Tests.csproj
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/MariaDbTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/RedisTestcontainerTest.cs
Labels: enhancement

#765 fix: Use TCP to connect to the MySQL module
  src/Testcontainers.MariaDb/MariaDbBuilder.cs
  src/Testcontainers.MariaDb/MariaDbContainer.cs
  src/Testcontainers.MySql/MySqlBuilder.cs
  src/Testcontainers.MySql/MySqlContainer.cs
Labels: chore

#760 feat: Add MinIO module
  Testcontainers.sln
  src/Testcontainers.Minio/.editorconfig
  src/Testcontainers.Minio/MinioBuilder.cs
  src/Testcontainers.Minio/MinioConfiguration.cs
  src/Testcontainers.Minio/MinioContainer.cs
  src/Testcontainers.Minio/Testcontainers.Minio.csproj
  src/Testcontainers.Minio/Usings.cs
  tests/Testcontainers.Minio.Tests/.editorconfig
  tests/Testcontainers.Minio.Tests/MinioContainerTests.cs
  tests/Testcontainers.Minio.Tests/Testcontainers.Minio.Tests.csproj
  tests/Testcontainers.Minio.Tests/Usings.cs
Labels: enhancement

#766 chore: Clean up MinIO module
  src/Testcontainers.MariaDb/MariaDbBuilder.cs
  src/Testcontainers.Minio/MinioBuilder.cs
  src/Testcontainers.Minio/MinioConfiguration.cs
  src/Testcontainers.Minio/MinioContainer.cs
  src/Testcontainers.Minio/Usings.cs
  tests/Testcontainers.Minio.Tests/MinioContainerTests.cs
  tests/Testcontainers.Minio.Tests/Testcontainers.Minio.Tests.csproj
  tests/Testcontainers.Minio.Tests/Usings.cs
Labels: chore

#770 feat: Replace Oracle module
  Packages.props
  Testcontainers.sln
  src/Testcontainers.Oracle/.editorconfig
  src/Testcontainers.Oracle/OracleBuilder.cs
  src/Testcontainers.Oracle/OracleConfiguration.cs
  src/Testcontainers.Oracle/OracleContainer.cs
  src/Testcontainers.Oracle/Testcontainers.Oracle.csproj
  src/Testcontainers.Oracle/Usings.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/OracleTestcontainer.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/OracleTestcontainerConfiguration.cs
  tests/Testcontainers.Oracle.Tests/.editorconfig
  tests/Testcontainers.Oracle.Tests/OracleContainerTest.cs
  tests/Testcontainers.Oracle.Tests/Testcontainers.Oracle.Tests.csproj
  tests/Testcontainers.Oracle.Tests/Usings.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/Modules/Databases/OracleFixture.cs
  tests/Testcontainers.Tests/Testcontainers.Tests.csproj
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/OracleTestcontainerTest.cs
Labels: enhancement

#771 docs: Add section 'Implement a module'
  docs/modules/index.md
Labels: documentation

#772 feat: Replace PostgreSQL module
  Packages.props
  Testcontainers.sln
  src/Testcontainers.PostgreSql/.editorconfig
  src/Testcontainers.PostgreSql/PostgreSqlBuilder.cs
  src/Testcontainers.PostgreSql/PostgreSqlConfiguration.cs
  src/Testcontainers.PostgreSql/PostgreSqlContainer.cs
  src/Testcontainers.PostgreSql/Testcontainers.PostgreSql.csproj
  src/Testcontainers.PostgreSql/Usings.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/PostgreSqlTestcontainer.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/PostgreSqlTestcontainerConfiguration.cs
  tests/Testcontainers.PostgreSql.Tests/.editorconfig
  tests/Testcontainers.PostgreSql.Tests/PostgreSqlContainerTest.cs
  tests/Testcontainers.PostgreSql.Tests/Testcontainers.PostgreSql.Tests.csproj
  tests/Testcontainers.PostgreSql.Tests/Usings.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/Modules/Databases/PostgreSqlFixture.cs
  tests/Testcontainers.Tests/Testcontainers.Tests.csproj
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/PostgreSqlTestcontainerTest.cs
Labels: enhancement

#768 feat: Add DynamoDB module
  Testcontainers.sln
  src/Testcontainers.DynamoDb/.editorconfig
  src/Testcontainers.DynamoDb/DynamoDbBuilder.cs
  src/Testcontainers.DynamoDb/DynamoDbConfiguration.cs
  src/Testcontainers.DynamoDb/DynamoDbContainer.cs
  src/Testcontainers.DynamoDb/Testcontainers.DynamoDb.csproj
  src/Testcontainers.DynamoDb/Usings.cs
  tests/Testcontainers.DynamoDb.Tests/DynamoDbContainerTests.cs
  tests/Testcontainers.DynamoDb.Tests/Testcontainers.DynamoDb.Tests.csproj
  tests/Testcontainers.DynamoDb.Tests/Usings.cs
Labels: enhancement

#774 chore: Clean up DynamoDB module
  src/Testcontainers.DynamoDb/DynamoDbBuilder.cs
  src/Testcontainers.DynamoDb/DynamoDbContainer.cs
  src/Testcontainers.DynamoDb/Testcontainers.DynamoDb.csproj
  src/Testcontainers.DynamoDb/Usings.cs
  src/Testcontainers.Minio/MinioBuilder.cs
  tests/Testcontainers.DynamoDb.Tests/.editorconfig
  tests/Testcontainers.DynamoDb.Tests/DynamoDbContainerTest.cs
  tests/Testcontainers.DynamoDb.Tests/DynamoDbContainerTests.cs
  tests/Testcontainers.DynamoDb.Tests/Testcontainers.DynamoDb.Tests.csproj
  tests/Testcontainers.DynamoDb.Tests/Usings.cs
  tests/Testcontainers.Minio.Tests/MinioContainerTest.cs
Labels: chore

#776 feat: Replace MongoDB module
  Testcontainers.sln
  examples/WeatherForecast/WeatherForecast.sln
  src/Testcontainers.Minio/MinioContainer.cs
  src/Testcontainers.MongoDb/.editorconfig
  src/Testcontainers.MongoDb/MongoDbBuilder.cs
  src/Testcontainers.MongoDb/MongoDbConfiguration.cs
  src/Testcontainers.MongoDb/MongoDbContainer.cs
  src/Testcontainers.MongoDb/MongoDbShellCommand.cs
  src/Testcontainers.MongoDb/Testcontainers.MongoDb.csproj
  src/Testcontainers.MongoDb/Usings.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/MongoDbTestcontainer.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/MongoDbTestcontainerConfiguration.cs
  tests/Testcontainers.Commons/CommonCredentials.cs
  tests/Testcontainers.DynamoDb.Tests/DynamoDbContainerTest.cs
  tests/Testcontainers.Minio.Tests/MinioContainerTest.cs
  tests/Testcontainers.MongoDb.Tests/.editorconfig
  tests/Testcontainers.MongoDb.Tests/MongoDbContainerTest.cs
  tests/Testcontainers.MongoDb.Tests/Testcontainers.MongoDb.Tests.csproj
  tests/Testcontainers.MongoDb.Tests/Usings.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/Modules/Databases/MongoDbFixture.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/Modules/Databases/MongoDbNoAuthFixture.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/MongoDbTestcontainerTest.cs
Labels: enhancement

#779 feat: Replace CouchDb module
  Packages.props
  Testcontainers.sln
  examples/WeatherForecast/WeatherForecast.sln
  src/Testcontainers.CouchDb/.editorconfig
  src/Testcontainers.CouchDb/CouchDbBuilder.cs
  src/Testcontainers.CouchDb/CouchDbConfiguration.cs
  src/Testcontainers.CouchDb/CouchDbContainer.cs
  src/Testcontainers.CouchDb/Testcontainers.CouchDb.csproj
  src/Testcontainers.CouchDb/Usings.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/CouchDbTestcontainer.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/CouchDbTestcontainerConfiguration.cs
  tests/Testcontainers.CouchDb.Tests/.editorconfig
  tests/Testcontainers.CouchDb.Tests/CouchDbContainerTest.cs
  tests/Testcontainers.CouchDb.Tests/Testcontainers.CouchDb.Tests.csproj
  tests/Testcontainers.CouchDb.Tests/Usings.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/Modules/Databases/CouchDbFixture.cs
  tests/Testcontainers.Tests/Testcontainers.Tests.csproj
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/CouchDbTestcontainerTest.cs
Labels: enhancement

#781 chore: Clean up LocalStack module
  Testcontainers.sln
  src/Testcontainers.LocalStack/LocalStackBuilder.cs
  src/Testcontainers.LocalStack/LocalStackContainer.cs
  src/Testcontainers.LocalStack/Testcontainers.LocalStack.csproj
  src/Testcontainers.LocalStack/Usings.cs
  tests/Testcontainers.DynamoDb.Tests/DynamoDbContainerTest.cs
  tests/Testcontainers.LocalStack.Tests/LocalStackContainerTests.cs
  tests/Testcontainers.LocalStack.Tests/Testcontainers.LocalStack.Tests.csproj
  tests/Testcontainers.LocalStack.Tests/Usings.cs
  tests/Testcontainers.Minio.Tests/MinioContainerTest.cs
Labels: chore

#785 feat: Replace Neo4j module
  Testcontainers.sln
  src/Testcontainers.LocalStack/LocalStackContainer.cs
  src/Testcontainers.Neo4j/.editorconfig
  src/Testcontainers.Neo4j/Neo4jBuilder.cs
  src/Testcontainers.Neo4j/Neo4jConfiguration.cs
  src/Testcontainers.Neo4j/Neo4jContainer.cs
  src/Testcontainers.Neo4j/Testcontainers.Neo4j.csproj
  src/Testcontainers.Neo4j/Usings.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/Neo4jTestcontainer.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/Neo4jTestcontainerConfiguration.cs
  src/Testcontainers/_OBSOLETE_/Modules/MessageBrokers/LocalStackTestcontainer.cs
  src/Testcontainers/_OBSOLETE_/Modules/MessageBrokers/LocalStackTestcontainerConfiguration.cs
  tests/Testcontainers.Commons/CommonCredentials.cs
  tests/Testcontainers.LocalStack.Tests/Usings.cs
  tests/Testcontainers.Neo4j.Tests/.editorconfig
  tests/Testcontainers.Neo4j.Tests/Neo4jContainerTest.cs
  tests/Testcontainers.Neo4j.Tests/Testcontainers.Neo4j.Tests.csproj
  tests/Testcontainers.Neo4j.Tests/Usings.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/Modules/Databases/Neo4jFixture.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/Modules/MessageBrokers/LocalStackFixture.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/Neo4jTestcontainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/MessageBrokers/LocalStackTestcontainerTest.cs
Labels: enhancement

#790 feat: Replace Elasticsearch module
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  Packages.props
  Testcontainers.sln
  src/Testcontainers.CouchDb/CouchDbBuilder.cs
  src/Testcontainers.DynamoDb/DynamoDbContainer.cs
  src/Testcontainers.Elasticsearch/.editorconfig
  src/Testcontainers.Elasticsearch/ElasticsearchBuilder.cs
  src/Testcontainers.Elasticsearch/ElasticsearchConfiguration.cs
  src/Testcontainers.Elasticsearch/ElasticsearchContainer.cs
  src/Testcontainers.Elasticsearch/Testcontainers.Elasticsearch.csproj
  src/Testcontainers.Elasticsearch/Usings.cs
  src/Testcontainers.MariaDb/MariaDbBuilder.cs
  src/Testcontainers.Minio/MinioContainer.cs
  src/Testcontainers.MsSql/MsSqlBuilder.cs
  src/Testcontainers.MySql/MySqlBuilder.cs
  src/Testcontainers.PostgreSql/PostgreSqlBuilder.cs
  src/Testcontainers.RabbitMq/RabbitMqBuilder.cs
  src/Testcontainers.RavenDb/RavenDbContainer.cs
  src/Testcontainers.Redis/RedisBuilder.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/ElasticsearchTestcontainer.cs
  src/Testcontainers/_OBSOLETE_/Modules/Databases/ElasticsearchTestcontainerConfiguration.cs
  tests/Testcontainers.DynamoDb.Tests/DynamoDbContainerTest.cs
  tests/Testcontainers.Elasticsearch.Tests/.editorconfig
  tests/Testcontainers.Elasticsearch.Tests/ElasticsearchContainerTest.cs
  tests/Testcontainers.Elasticsearch.Tests/Testcontainers.Elasticsearch.Tests.csproj
  tests/Testcontainers.Elasticsearch.Tests/Usings.cs
  tests/Testcontainers.Minio.Tests/MinioContainerTest.cs
  tests/Testcontainers.RavenDb.Tests/RavenDbContainerTest.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/Modules/Databases/ElasticsearchFixture.cs
  tests/Testcontainers.Tests/Testcontainers.Tests.csproj
  tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/ElasticsearchTestcontainerTest.cs
Labels: enhancement

#789 fix(#783): Dispose container while Resource Reaper is disabled
  src/Testcontainers/Clients/DefaultLabels.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Containers/DockerContainer.cs
Labels: bug

#778 feat: Add EventStoreDb module
  Testcontainers.sln
  src/Testcontainers.EventStoreDb/.editorconfig
  src/Testcontainers.EventStoreDb/EventStoreDbBuilder.cs
  src/Testcontainers.EventStoreDb/EventStoreDbConfiguration.cs
  src/Testcontainers.EventStoreDb/EventStoreDbContainer.cs
  src/Testcontainers.EventStoreDb/Testcontainers.EventStoreDb.csproj
  src/Testcontainers.EventStoreDb/Usings.cs
  tests/Testcontainers.EventStoreDb.Tests/.editorconfig
  tests/Testcontainers.EventStoreDb.Tests/EventStoreDbContainerTest.cs
  tests/Testcontainers.EventStoreDb.Tests/Testcontainers.EventStoreDb.Tests.csproj
  tests/Testcontainers.EventStoreDb.Tests/Usings.cs
Labels: enhancement

#792 chore: Clean up EventStoreDb module
  Testcontainers.sln
  src/Testcontainers.EventStoreDb/EventStoreDbBuilder.cs
  src/Testcontainers.EventStoreDb/EventStoreDbConfiguration.cs
  src/Testcontainers.EventStoreDb/EventStoreDbContainer.cs
  src/Testcontainers.EventStoreDb/Testcontainers.EventStoreDb.csproj
  src/Testcontainers.EventStoreDb/Usings.cs
  tests/Testcontainers.EventStoreDb.Tests/EventStoreDbContainerTest.cs
  tests/Testcontainers.EventStoreDb.Tests/Testcontainers.EventStoreDb.Tests.csproj
  tests/Testcontainers.EventStoreDb.Tests/Usings.cs
Labels: chore

#793 feat: Replace output consumer with `IContainer.GetLogsAsync(DateTime, DateTime, bool, CancellationToken)`
  docs/api/create_docker_container.md
  src/Testcontainers.Elasticsearch/ElasticsearchBuilder.cs
  src/Testcontainers.EventStoreDb/EventStoreDbBuilder.cs
  src/Testcontainers.MongoDb/MongoDbBuilder.cs
  src/Testcontainers.Oracle/OracleBuilder.cs
  src/Testcontainers.RabbitMq/RabbitMqBuilder.cs
  src/Testcontainers.RavenDb/RavenDbBuilder.cs
  src/Testcontainers/BackwardCompatibility/BackwardsCompatibility.cs
  src/Testcontainers/Builders/IContainerBuilder`2.cs
  src/Testcontainers/Clients/DockerContainerOperations.cs
  src/Testcontainers/Clients/IDockerContainerOperations.cs
  src/Testcontainers/Clients/ITestcontainersClient.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Configurations/WaitStrategies/IWaitForContainerOS.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilMessageIsLogged.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitForContainerOS.cs
  src/Testcontainers/Containers/DockerContainer.cs
  src/Testcontainers/Containers/IContainer.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilMessageIsLoggedTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Windows/TestcontainersContainerTest.cs
Labels: enhancement

#791 fix: Wait until container ports are mapped, removed generated credentials
  Packages.props
  build.cake
  src/Testcontainers.CouchDb/CouchDbBuilder.cs
  src/Testcontainers.Elasticsearch/ElasticsearchBuilder.cs
  src/Testcontainers.Elasticsearch/Usings.cs
  src/Testcontainers.MariaDb/MariaDbBuilder.cs
  src/Testcontainers.Minio/MinioBuilder.cs
  src/Testcontainers.MongoDb/MongoDbBuilder.cs
  src/Testcontainers.MsSql/MsSqlBuilder.cs
  src/Testcontainers.MySql/MySqlBuilder.cs
  src/Testcontainers.Oracle/OracleBuilder.cs
  src/Testcontainers.PostgreSql/PostgreSqlBuilder.cs
  src/Testcontainers.RabbitMq/RabbitMqBuilder.cs
  src/Testcontainers/Clients/ITestcontainersClient.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilOperationIsSucceeded.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitStrategy.cs
  src/Testcontainers/Containers/DockerContainer.cs
  tests/Testcontainers.CouchDb.Tests/CouchDbContainerTest.cs
  tests/Testcontainers.CouchDb.Tests/Usings.cs
  tests/Testcontainers.Elasticsearch.Tests/ElasticsearchContainerTest.cs
  tests/Testcontainers.Elasticsearch.Tests/Usings.cs
  tests/Testcontainers.RabbitMq.Tests/RabbitMqContainerTest.cs
  tests/Testcontainers.RabbitMq.Tests/Usings.cs
  tests/Testcontainers.Tests/Unit/Configurations/TestcontainersWaitStrategyTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilOperationIsSucceededTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Windows/TestcontainersContainerTest.cs
Labels: bug, enhancement

#796 feat: Add Redpanda module
  Testcontainers.sln
  src/Testcontainers.Redpanda/.editorconfig
  src/Testcontainers.Redpanda/RedpandaBuilder.cs
  src/Testcontainers.Redpanda/RedpandaConfiguration.cs
  src/Testcontainers.Redpanda/RedpandaContainer.cs
  src/Testcontainers.Redpanda/Testcontainers.Redpanda.csproj
  src/Testcontainers.Redpanda/Usings.cs
  tests/Testcontainers.Redpanda.Tests/.editorconfig
  tests/Testcontainers.Redpanda.Tests/RedpandaContainerTest.cs
  tests/Testcontainers.Redpanda.Tests/Testcontainers.Redpanda.Tests.csproj
  tests/Testcontainers.Redpanda.Tests/Usings.cs
Labels: enhancement

#800 fix: Coverlet 'Unable to read beyond end of stream' IOException
  .github/workflows/cicd.yml
  Packages.props
  Testcontainers.sln
  Testcontainers.sln.DotSettings
  build.cake
  examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecast.InProcess.Tests.csproj
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecast.Tests.csproj
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Networks/DockerNetwork.cs
  tests/Testcontainers.Commons/TestSession.cs
  tests/Testcontainers.CouchDb.Tests/Testcontainers.CouchDb.Tests.csproj
  tests/Testcontainers.Couchbase.Tests/Testcontainers.Couchbase.Tests.csproj
  tests/Testcontainers.DynamoDb.Tests/Testcontainers.DynamoDb.Tests.csproj
  tests/Testcontainers.Elasticsearch.Tests/Testcontainers.Elasticsearch.Tests.csproj
  tests/Testcontainers.EventStoreDb.Tests/Testcontainers.EventStoreDb.Tests.csproj
  tests/Testcontainers.LocalStack.Tests/LocalStackContainerTests.cs
  tests/Testcontainers.LocalStack.Tests/Testcontainers.LocalStack.Tests.csproj
  tests/Testcontainers.MariaDb.Tests/Testcontainers.MariaDb.Tests.csproj
  tests/Testcontainers.Minio.Tests/Testcontainers.Minio.Tests.csproj
  tests/Testcontainers.MongoDb.Tests/Testcontainers.MongoDb.Tests.csproj
  tests/Testcontainers.MsSql.Tests/Testcontainers.MsSql.Tests.csproj
  tests/Testcontainers.MySql.Tests/Testcontainers.MySql.Tests.csproj
  tests/Testcontainers.Neo4j.Tests/Testcontainers.Neo4j.Tests.csproj
  tests/Testcontainers.Oracle.Tests/Testcontainers.Oracle.Tests.csproj
  tests/Testcontainers.Platform.Linux.Tests/Testcontainers.Platform.Linux.Tests.csproj
  tests/Testcontainers.Platform.Windows.Tests/Testcontainers.Platform.Windows.Tests.csproj
  tests/Testcontainers.PostgreSql.Tests/Testcontainers.PostgreSql.Tests.csproj
  tests/Testcontainers.RabbitMq.Tests/Testcontainers.RabbitMq.Tests.csproj
  tests/Testcontainers.RavenDb.Tests/Testcontainers.RavenDb.Tests.csproj
  tests/Testcontainers.Redis.Tests/Testcontainers.Redis.Tests.csproj
  tests/Testcontainers.Redpanda.Tests/Testcontainers.Redpanda.Tests.csproj
  tests/Testcontainers.ResourceReaper.Tests/Testcontainers.ResourceReaper.Tests.csproj
  tests/Testcontainers.Tests/Testcontainers.Tests.csproj
Labels: chore

#804 chore!: Remove legacy TestcontainersNetworkBuilder, IDockerNetwork
  src/Testcontainers/BackwardCompatibility/BackwardsCompatibility.cs
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Builders/IContainerBuilder`2.cs
  src/Testcontainers/Networks/DockerNetwork.cs
  src/Testcontainers/Networks/INetwork.cs
  tests/Testcontainers.Kafka.Tests/Testcontainers.Kafka.Tests.csproj
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/NetworkFixture.cs
  tests/Testcontainers.Tests/Unit/Configurations/TestcontainersAccessInformationTest.cs
  tests/Testcontainers.Tests/Unit/Networks/TestcontainerNetworkBuilderTest.cs
Labels: breaking change

#805 chore!: Remove legacy TestcontainersVolumeBuilder, IDockerVolume
  src/Testcontainers.PostgreSql/PostgreSqlBuilder.cs
  src/Testcontainers/BackwardCompatibility/BackwardsCompatibility.cs
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Builders/IContainerBuilder`2.cs
  src/Testcontainers/Volumes/DockerVolume.cs
  src/Testcontainers/Volumes/IVolume.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/VolumeFixture.cs
  tests/Testcontainers.Tests/Unit/Configurations/TestcontainersAccessInformationTest.cs
  tests/Testcontainers.Tests/Unit/Volumes/TestcontainersVolumeBuilderTest.cs
  tests/Testcontainers.Tests/Unit/Volumes/TestcontainersVolumeTest.cs
Labels: breaking change

#806 docs: Update Testcontainers for Node docs link
  docs/index.md
Labels: documentation

#807 docs: Add community links
  .github/release-drafter.yml
  docs/community-logos/github.svg
  docs/community-logos/slack.svg
  docs/community-logos/stackoverflow.svg
  docs/community-logos/twitter.svg
  docs/css/extra.css
  docs/index.md
  docs/language-logos/haskell.svg
  docs/theme/main.html
  docs/theme/partials/nav.html
  mkdocs.yml
Labels: documentation

#808 chore!: Remove legacy IDockerImage
  src/Testcontainers.Couchbase/CouchbaseBuilder.cs
  src/Testcontainers/BackwardCompatibility/BackwardsCompatibility.cs
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Builders/IContainerBuilder`2.cs
  src/Testcontainers/Builders/IImageFromDockerfileBuilder`1.cs
  src/Testcontainers/Builders/ImageFromDockerfileBuilder.cs
  src/Testcontainers/Images/IImage.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/ProtectDockerDaemonSocket.cs
  tests/Testcontainers.Tests/Fixtures/Images/DockerImageFixtureSerializable.cs
  tests/Testcontainers.Tests/Unit/Configurations/DockerImageNameSubstitutionTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/DockerRegistryAuthenticationProviderTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilContainerIsHealthyTest.cs
  tests/Testcontainers.Tests/Unit/Images/TestcontainersImageTest.cs
Labels: breaking change

#809 chore!: Remove legacy WithCreateContainerParametersModifier(Action<CreateContainerParameters>)
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Builders/IContainerBuilder`2.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerTest.cs
Labels: breaking change
