Repository testcontainers/testcontainers-dotnet, pull requests merged in 2023-03, with the labels that each got.

#812 feat: Add SQL Edge module
  Testcontainers.sln
  src/Testcontainers.SqlEdge/.editorconfig
  src/Testcontainers.SqlEdge/SqlEdgeBuilder.cs
  src/Testcontainers.SqlEdge/SqlEdgeConfiguration.cs
  src/Testcontainers.SqlEdge/SqlEdgeContainer.cs
  src/Testcontainers.SqlEdge/Testcontainers.SqlEdge.csproj
  src/Testcontainers.SqlEdge/Usings.cs
  src/Testcontainers/Clients/ContainerConfigurationConverter.cs
  tests/Testcontainers.SqlEdge.Tests/.editorconfig
  tests/Testcontainers.SqlEdge.Tests/SqlEdgeContainerTest.cs
  tests/Testcontainers.SqlEdge.Tests/Testcontainers.SqlEdge.Tests.csproj
  tests/Testcontainers.SqlEdge.Tests/Usings.cs
Labels: enhancement

#815 feat: Sign assemblies with a strong name
  .gitattributes
  .github/workflows/codeql-analysis.yml
  Directory.Build.props
  Packages.props
  Testcontainers.sln
  build.cake
  src/Testcontainers.MongoDb/MongoDbBuilder.cs
  src/Testcontainers.MongoDb/MongoDbContainer.cs
  src/Testcontainers/BackwardCompatibility/BackwardsCompatibility.cs
  src/Testcontainers/Builders/IImageFromDockerfileBuilder`1.cs
  src/Testcontainers/Images/DockerImage.cs
  src/strongname.pub
  src/strongname.snk
  tests/Directory.Build.props
  tests/Testcontainers.Commons/Testcontainers.Commons.csproj
  tests/Testcontainers.Tests/Testcontainers.Tests.csproj
Labels: enhancement

#816 docs: Add best practices
  docs/api/best_practices.md
  mkdocs.yml
Labels: documentation

#822 feat: Prepare next release cycle (3.1.0)
  Directory.Build.props
Labels: chore

#823 docs: Update the documentation and WeatherForecast example
  Directory.Build.props
  docs/api/create_docker_container.md
  docs/modules/index.md
  docs/modules/postgres.md
  examples/WeatherForecast/Packages.props
  examples/WeatherForecast/src/WeatherForecast/DatabaseContainer.cs
  examples/WeatherForecast/src/WeatherForecast/DatabaseContainerConfiguration.cs
  examples/WeatherForecast/src/WeatherForecast/WeatherForecast.csproj
  examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecastTest.cs
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastContainer.cs
Labels: documentation

#839 fix: Log Docker image build progress messages
  src/Testcontainers/BackwardCompatibility/BackwardsCompatibility.cs
  src/Testcontainers/Clients/TraceProgress.cs
  src/Testcontainers/Logging.cs
Labels: bug

#838 docs: Update ASP.NET Core Blazor out-off-process example
  docs/examples/aspnet.md
  docs/examples/compose.md
  docs/modules/index.md
  docs/modules/postgres.md
  examples/WeatherForecast/src/WeatherForecast/Program.cs
  examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecastTest.cs
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastContainer.cs
Labels: documentation

#840 chore: Update Redpanda image
  src/Testcontainers.Redpanda/RedpandaBuilder.cs
Labels: chore

#832 feat: Add container builder member to depend on other Docker resources
  docs/api/create_docker_container.md
  src/Testcontainers.CosmosDb/CosmosDbContainer.cs
  src/Testcontainers.MongoDb/MongoDbBuilder.cs
  src/Testcontainers.PostgreSql/PostgreSqlBuilder.cs
  src/Testcontainers.SqlEdge/SqlEdgeBuilder.cs
  src/Testcontainers/BackwardCompatibility/BackwardsCompatibility.cs
  src/Testcontainers/Builders/BuildConfiguration.cs
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Builders/IContainerBuilder`2.cs
  src/Testcontainers/Clients/DockerImageOperations.cs
  src/Testcontainers/Clients/DockerNetworkOperations.cs
  src/Testcontainers/Clients/DockerVolumeOperations.cs
  src/Testcontainers/Configurations/Containers/ContainerConfiguration.cs
  src/Testcontainers/Configurations/Containers/IContainerConfiguration.cs
  src/Testcontainers/Configurations/Volumes/BindMount.cs
  src/Testcontainers/Configurations/Volumes/FileResourceMapping.cs
  src/Testcontainers/Configurations/Volumes/IMount.cs
  src/Testcontainers/Configurations/Volumes/TmpfsMount.cs
  src/Testcontainers/Configurations/Volumes/VolumeMount.cs
  src/Testcontainers/Containers/DockerContainer.cs
  src/Testcontainers/Containers/IContainer.cs
  src/Testcontainers/Containers/ResourceReaper.cs
  src/Testcontainers/Images/FutureDockerImage.cs
  src/Testcontainers/Images/IFutureDockerImage.cs
  src/Testcontainers/Networks/DockerNetwork.cs
  src/Testcontainers/Networks/INetwork.cs
  src/Testcontainers/Resource.cs
  src/Testcontainers/Volumes/DockerVolume.cs
  src/Testcontainers/Volumes/IVolume.cs
  src/Testcontainers/_OBSOLETE_/Modules/HostedServiceConfiguration.cs
  src/Testcontainers/_OBSOLETE_/Modules/HostedServiceContainer.cs
  src/Testcontainers/_OBSOLETE_/Modules/IDatabaseScript.cs
  src/Testcontainers/_OBSOLETE_/Modules/TestcontainerDatabase.cs
  src/Testcontainers/_OBSOLETE_/Modules/TestcontainerDatabaseConfiguration.cs
  src/Testcontainers/_OBSOLETE_/TestcontainersBuilderDatabaseExtension.cs
  tests/Testcontainers.Platform.Linux.Tests/DependsOnTest.cs
  tests/Testcontainers.Platform.Linux.Tests/Usings.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/AlpineFixture.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/Modules/DatabaseFixture`2.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/ProtectDockerDaemonSocket.cs
  tests/Testcontainers.Tests/Unit/Builders/BuildConfigurationTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/DockerImageNameSubstitutionTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/TestcontainersAccessInformationTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/TestcontainersAccessNotPreConfiguredTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilHttpRequestIsSucceededTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/CopyResourceMappingContainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/GetContainerLogsTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/ReadFileFromContainerTest.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerTest.cs
  tests/Testcontainers.Tests/Unit/Networks/TestcontainerNetworkBuilderTest.cs
  tests/Testcontainers.Tests/Unit/Networks/TestcontainersNetworkTest.cs
  tests/Testcontainers.Tests/Unit/Volumes/TestcontainersVolumeBuilderTest.cs
  tests/Testcontainers.Tests/Unit/Volumes/TestcontainersVolumeTest.cs
Labels: enhancement

#849 fix: KafkaException (timeout) while creating a topic
  src/Testcontainers.Kafka/KafkaBuilder.cs
Labels: bug

#852 feat: Always use Docker's assigned random host port (Ryuk)
  docs/examples/dind.md
  mkdocs.yml
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  src/Testcontainers/Containers/ResourceReaper.cs
Labels: enhancement
