Repository testcontainers/testcontainers-dotnet, pull requests merged in 2024-12, with the labels that each got.

#1310 fix: Postpone exception in `DbContainerFixture` to match the behavior of `ContainerFixture`
  src/Testcontainers.Xunit/DbContainerFixture.cs
  src/Testcontainers.Xunit/DbContainerTest.cs
  src/Testcontainers.Xunit/DbContainerTestMethods.cs
Labels: bug

#1313 feat: Set ryuk.container.privileged default value to true
  docs/custom_configuration/index.md
  src/Testcontainers/Builders/DockerDesktopEndpointAuthenticationProvider.cs
  src/Testcontainers/Builders/TestcontainersEndpointAuthenticationProvider.cs
  src/Testcontainers/Configurations/CustomConfiguration.cs
  src/Testcontainers/Configurations/EnvironmentConfiguration.cs
  src/Testcontainers/Configurations/ICustomConfiguration.cs
  src/Testcontainers/Configurations/PropertiesFileConfiguration.cs
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  tests/Testcontainers.Tests/Unit/Configurations/CustomConfigurationTest.cs
Labels: enhancement

#1309 feat: Add Azure Service Bus module
  .github/workflows/cicd.yml
  Directory.Packages.props
  Testcontainers.sln
  docs/modules/index.md
  src/Testcontainers.ServiceBus/.editorconfig
  src/Testcontainers.ServiceBus/ServiceBusBuilder.cs
  src/Testcontainers.ServiceBus/ServiceBusConfiguration.cs
  src/Testcontainers.ServiceBus/ServiceBusContainer.cs
  src/Testcontainers.ServiceBus/Testcontainers.ServiceBus.csproj
  src/Testcontainers.ServiceBus/Usings.cs
  src/Testcontainers/Containers/IDatabaseContainer.cs
  tests/Testcontainers.ServiceBus.Tests/.editorconfig
  tests/Testcontainers.ServiceBus.Tests/ServiceBusContainerTest.cs
  tests/Testcontainers.ServiceBus.Tests/Testcontainers.ServiceBus.Tests.csproj
  tests/Testcontainers.ServiceBus.Tests/Usings.cs
Labels: enhancement, module

#1317 fix: Make Testcontainers.XunitV3 publishable
  Directory.Packages.props
  src/Testcontainers.XunitV3/Testcontainers.XunitV3.csproj
Labels: chore

#1320 fix: Load PKCS#12 correctly for mTLS on Windows in .NET 9
  src/Testcontainers/Builders/MTlsEndpointAuthenticationProvider.cs
Labels: bug
