Repository testcontainers/testcontainers-dotnet, pull requests merged in 2024-11, with the labels that each got.

#1292 chore: Replace Docker.DotNet with the Testcontainers organization's build
  Directory.Packages.props
  src/Testcontainers/Clients/DockerContainerOperations.cs
  src/Testcontainers/Testcontainers.csproj
Labels: chore

#1287 fix: Prepend Docker Hub namespace to repository
  src/Testcontainers/Images/DockerImage.cs
  tests/Testcontainers.Tests/Fixtures/Images/DockerImageFixture.cs
Labels: bug

#1295 chore: Run each test project on a separate runner
  .cake-scripts/parameters.cake
  .cake-scripts/paths.cake
  .cake-scripts/version.cake
  .config/dotnet-tools.json
  .github/workflows/cicd.yml
  .github/workflows/test-report.yml
  build.cake
  tests/Testcontainers.Platform.Linux.Tests/TarOutputMemoryStreamTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilHttpRequestIsSucceededTest.cs
Labels: chore

#1297 fix: Add HTTP wait strategy to prevent race-condition in TarOutputMemoryStreamTest
  src/Testcontainers.WebDriver/WebDriverBuilder.cs
  tests/Testcontainers.Platform.Linux.Tests/TarOutputMemoryStreamTest.cs
Labels: bug

#1299 fix: Add HTTP wait strategy to prevent race-condition in WaitUntilHttpRequestIsSucceededTest
  .github/settings.yml
  tests/Testcontainers.Commons/CommonImages.cs
  tests/Testcontainers.Platform.Linux.Tests/TarOutputMemoryStreamTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilHttpRequestIsSucceededTest.cs
Labels: bug

#1300 docs: Add low level API access
  .github/workflows/cicd.yml
  .github/workflows/codeql-analysis.yml
  docs/api/low_level_api_access.md
  mkdocs.yml
Labels: documentation

#1304 fix: Do not pre-pull scratch image
  src/Testcontainers/Clients/TestcontainersClient.cs
  tests/Testcontainers.Tests/Assets/.dockerignore
  tests/Testcontainers.Tests/Assets/scratch/Dockerfile
  tests/Testcontainers.Tests/Unit/Images/ImageFromDockerfileTest.cs
Labels: bug

#1305 chore: Add test to ensure that all test projects are configured for CI
  tests/Testcontainers.Tests/ContinuousIntegration/JobsTest.cs
Labels: chore

#1165 feat: Introduce a new Testcontainers.Xunit package
  .github/workflows/cicd.yml
  Directory.Packages.props
  Testcontainers.sln
  docs/test_frameworks/xunit_net.md
  mkdocs.yml
  src/Testcontainers.Xunit/.editorconfig
  src/Testcontainers.Xunit/ContainerFixture.cs
  src/Testcontainers.Xunit/ContainerLifetime.cs
  src/Testcontainers.Xunit/ContainerTest.cs
  src/Testcontainers.Xunit/DbContainerFixture.cs
  src/Testcontainers.Xunit/DbContainerTest.cs
  src/Testcontainers.Xunit/DbContainerTestMethods.cs
  src/Testcontainers.Xunit/IDbContainerTestMethods.cs
  src/Testcontainers.Xunit/Logger.cs
  src/Testcontainers.Xunit/MessageSinkLogger.cs
  src/Testcontainers.Xunit/NullScope.cs
  src/Testcontainers.Xunit/TestOutputLogger.cs
  src/Testcontainers.Xunit/Testcontainers.Xunit.csproj
  src/Testcontainers.Xunit/Usings.cs
  src/Testcontainers.XunitV3/.editorconfig
  src/Testcontainers.XunitV3/Testcontainers.XunitV3.csproj
  tests/Testcontainers.Databases.Tests/DatabasesContainerTest.cs
  tests/Testcontainers.Xunit.Tests/.editorconfig
  tests/Testcontainers.Xunit.Tests/AlphabeticalTestCaseOrderer.cs
  tests/Testcontainers.Xunit.Tests/Chinook_PostgreSql_AutoIncrementPKs.sql
  tests/Testcontainers.Xunit.Tests/PostgreSqlContainer.cs
  tests/Testcontainers.Xunit.Tests/RedisContainerTest`1.cs
  tests/Testcontainers.Xunit.Tests/RedisContainerTest`2.cs
  tests/Testcontainers.Xunit.Tests/Testcontainers.Xunit.Tests.csproj
  tests/Testcontainers.Xunit.Tests/Usings.cs
Labels: enhancement
