Repository testcontainers/testcontainers-dotnet, pull requests merged in 2024-08, with the labels that each got.

#1226 feat: Log Docker daemon labels if present
  src/Testcontainers/Clients/DockerApiClient.cs
Labels: enhancement

#1213 fix: Add Keycloak health port 9000 starting from major version 25
  src/Testcontainers.Keycloak/KeycloakBuilder.cs
  src/Testcontainers.Keycloak/Usings.cs
  src/Testcontainers/Images/DockerImage.cs
  src/Testcontainers/Images/FutureDockerImage.cs
  src/Testcontainers/Images/IImage.cs
  tests/Testcontainers.Keycloak.Tests/KeycloakContainerTest.cs
  tests/Testcontainers.Keycloak.Tests/Usings.cs
  tests/Testcontainers.Tests/Fixtures/Images/HealthCheckFixture.cs
  tests/Testcontainers.Tests/Unit/Images/TestcontainersImageTest.cs
Labels: bug

#1231 feat: Improve parsing of Docker image tag version `MatchVersion(Predicate<Version>)`
  src/Testcontainers/Images/DockerImage.cs
  tests/Testcontainers.Tests/Unit/Images/TestcontainersImageTest.cs
Labels: enhancement

#1230 chore: Change global.json roll-forward policy from `latestPatch` to `latestMinor`
  global.json
Labels: chore

#1234 feat: Detect CSharp, FSharp and Visual Basic projects
  .cake-scripts/version.cake
  build.cake
  src/Testcontainers/Builders/CommonDirectoryPath.cs
  src/Testcontainers/Images/DockerImage.cs
  tests/Testcontainers.Tests/Unit/Builders/CommonDirectoryPathTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/DockerEndpointAuthenticationProviderTest.cs
Labels: enhancement

#1196 feat: Add MongoDB replica set support
  docs/modules/mongodb.md
  src/Testcontainers.MongoDb/MongoDbBuilder.cs
  src/Testcontainers.MongoDb/MongoDbConfiguration.cs
  src/Testcontainers/Images/DockerImage.cs
  tests/Testcontainers.MongoDb.Tests/MongoDbContainerTest.cs
Labels: enhancement, module

#1221 fix: Get sqlcmd utility file path from container instead of const file path
  src/Testcontainers.MsSql/MsSqlBuilder.cs
  src/Testcontainers.MsSql/MsSqlContainer.cs
  tests/Testcontainers.MsSql.Tests/MsSqlContainerTest.cs
  tests/Testcontainers.MsSql.Tests/Usings.cs
Labels: bug, module

#1245 docs: Use codeinclude in module examples
  docs/examples/aspnet.md
  docs/modules/_call_out_test_projects.md
  docs/modules/elasticsearch.md
  docs/modules/index.md
  docs/modules/mongodb.md
  docs/modules/mssql.md
  docs/modules/neo4j.md
  docs/modules/postgres.md
  docs/modules/pulsar.md
  docs/modules/rabbitmq.md
  mkdocs.yml
  tests/Testcontainers.Elasticsearch.Tests/ElasticsearchContainerTest.cs
  tests/Testcontainers.Elasticsearch.Tests/Testcontainers.Elasticsearch.Tests.csproj
  tests/Testcontainers.MongoDb.Tests/MongoDbContainerTest.cs
  tests/Testcontainers.MongoDb.Tests/Testcontainers.MongoDb.Tests.csproj
  tests/Testcontainers.MsSql.Tests/MsSqlContainerTest.cs
  tests/Testcontainers.MsSql.Tests/Testcontainers.MsSql.Tests.csproj
  tests/Testcontainers.Neo4j.Tests/Neo4jContainerTest.cs
  tests/Testcontainers.Neo4j.Tests/Testcontainers.Neo4j.Tests.csproj
  tests/Testcontainers.PostgreSql.Tests/PostgreSqlContainerTest.cs
  tests/Testcontainers.PostgreSql.Tests/Testcontainers.PostgreSql.Tests.csproj
  tests/Testcontainers.Pulsar.Tests/PulsarContainerTest.cs
  tests/Testcontainers.Pulsar.Tests/Testcontainers.Pulsar.Tests.csproj
  tests/Testcontainers.RabbitMq.Tests/RabbitMqContainerTest.cs
  tests/Testcontainers.RabbitMq.Tests/Testcontainers.RabbitMq.Tests.csproj
Labels: documentation
