Repository testcontainers/testcontainers-dotnet, pull requests merged in 2024-06, with the labels that each got.

#1103 feat: Add Apache Pulsar module
  Directory.Packages.props
  Testcontainers.sln
  docs/modules/elasticsearch.md
  docs/modules/index.md
  docs/modules/mongodb.md
  docs/modules/neo4j.md
  docs/modules/pulsar.md
  mkdocs.yml
  src/Testcontainers.Pulsar/.editorconfig
  src/Testcontainers.Pulsar/PulsarBuilder.cs
  src/Testcontainers.Pulsar/PulsarConfiguration.cs
  src/Testcontainers.Pulsar/PulsarContainer.cs
  src/Testcontainers.Pulsar/Testcontainers.Pulsar.csproj
  src/Testcontainers.Pulsar/Usings.cs
  tests/Testcontainers.Databases.Tests/Usings.cs
  tests/Testcontainers.Pulsar.Tests/.editorconfig
  tests/Testcontainers.Pulsar.Tests/PulsarContainerTest.cs
  tests/Testcontainers.Pulsar.Tests/Testcontainers.Pulsar.Tests.csproj
  tests/Testcontainers.Pulsar.Tests/Usings.cs
Labels: enhancement, module

#1188 chore : Do not block async context on acquire lock
  Directory.Packages.props
  src/Testcontainers/Configurations/WaitStrategies/RetryLimitExceededException.cs
  src/Testcontainers/Containers/DockerContainer.cs
  src/Testcontainers/Images/FutureDockerImage.cs
  src/Testcontainers/Networks/DockerNetwork.cs
  src/Testcontainers/Resource.cs
  src/Testcontainers/Testcontainers.csproj
  src/Testcontainers/Volumes/DockerVolume.cs
  tests/Testcontainers.Platform.Linux.Tests/WaitStrategyTest.cs
Labels: chore

#1195 chore: Remove PulsarContainer.CreateAuthenticationTokenAsync(TimeSpan) default arg
  docs/modules/pulsar.md
  src/Testcontainers.Pulsar/PulsarContainer.cs
  tests/Testcontainers.Pulsar.Tests/PulsarContainerTest.cs
Labels: chore

#1202 chore: Remove obsolete UntilOperationIsSucceeded wait strategy
  src/Testcontainers.Pulsar/PulsarBuilder.cs
  src/Testcontainers/Builders/RootlessUnixEndpointAuthenticationProvider.cs
  src/Testcontainers/Configurations/WaitStrategies/IWaitForContainerOS.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilOperationIsSucceeded.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitForContainerOS.cs
  tests/Testcontainers.Tests/Unit/Configurations/WaitUntilOperationIsSucceededTest.cs
Labels: chore

#1203 fix: Trim relative path indicators from Dockerfile path
  src/Testcontainers/Builders/ImageFromDockerfileBuilder.cs
  tests/Testcontainers.Tests/Unit/Images/ImageFromDockerfileTest.cs
Labels: bug
