Repository testcontainers/testcontainers-dotnet, pull requests merged in 2024-05, with the labels that each got.

#1168 feat: Add wait strategy options
  docs/api/wait_strategies.md
  src/Testcontainers.Couchbase/CouchbaseBuilder.cs
  src/Testcontainers/Configurations/Containers/ContainerConfiguration.cs
  src/Testcontainers/Configurations/Containers/IContainerConfiguration.cs
  src/Testcontainers/Configurations/WaitStrategies/IWaitForContainerOS.cs
  src/Testcontainers/Configurations/WaitStrategies/IWaitStrategy.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitForContainerOS.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitForContainerUnix.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitForContainerWindows.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitStrategy.cs
  src/Testcontainers/Containers/DockerContainer.cs
Labels: enhancement, breaking change

#1169 feat: Add custom configuration for retries, interval and timeout
  docs/api/resource_reuse.md
  docs/custom_configuration/index.md
  src/Testcontainers/Builders/DockerDesktopEndpointAuthenticationProvider.cs
  src/Testcontainers/Builders/TestcontainersEndpointAuthenticationProvider.cs
  src/Testcontainers/Configurations/CustomConfiguration.cs
  src/Testcontainers/Configurations/EnvironmentConfiguration.cs
  src/Testcontainers/Configurations/ICustomConfiguration.cs
  src/Testcontainers/Configurations/PropertiesFileConfiguration.cs
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  src/Testcontainers/Configurations/WaitStrategies/RetryLimitExceededException.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitStrategy.cs
  tests/Testcontainers.Platform.Linux.Tests/WaitStrategyTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/CustomConfigurationTest.cs
Labels: enhancement

#1176 fix: Add default file permission (755 for image build)
  docs/api/create_docker_image.md
  src/Testcontainers/Images/DockerfileArchive.cs
Labels: bug

#1179 chore: Bump BouncyCastle.Cryptography
  Directory.Packages.props
Labels: dependencies
