Repository testcontainers/testcontainers-dotnet, pull requests merged in 2024-03, with the labels that each got.

#1133 feat: Add support for the target frameworks net6.0 and net8.0
  .devcontainer/devcontainer.json
  src/Templates/CSharp/Testcontainers.ModuleName/Testcontainers.ModuleName.csproj
  src/Testcontainers.ActiveMq/Testcontainers.ActiveMq.csproj
  src/Testcontainers.ArangoDb/Testcontainers.ArangoDb.csproj
  src/Testcontainers.Azurite/Testcontainers.Azurite.csproj
  src/Testcontainers.BigQuery/Testcontainers.BigQuery.csproj
  src/Testcontainers.Bigtable/Testcontainers.Bigtable.csproj
  src/Testcontainers.ClickHouse/Testcontainers.ClickHouse.csproj
  src/Testcontainers.CockroachDb/Testcontainers.CockroachDb.csproj
  src/Testcontainers.Consul/Testcontainers.Consul.csproj
  src/Testcontainers.CosmosDb/Testcontainers.CosmosDb.csproj
  src/Testcontainers.CouchDb/Testcontainers.CouchDb.csproj
  src/Testcontainers.Couchbase/Testcontainers.Couchbase.csproj
  src/Testcontainers.DynamoDb/Testcontainers.DynamoDb.csproj
  src/Testcontainers.Elasticsearch/Testcontainers.Elasticsearch.csproj
  src/Testcontainers.EventStoreDb/Testcontainers.EventStoreDb.csproj
  src/Testcontainers.FakeGcsServer/Testcontainers.FakeGcsServer.csproj
  src/Testcontainers.FirebirdSql/Testcontainers.FirebirdSql.csproj
  src/Testcontainers.Firestore/Testcontainers.Firestore.csproj
  src/Testcontainers.InfluxDb/Testcontainers.InfluxDb.csproj
  src/Testcontainers.JanusGraph/Testcontainers.JanusGraph.csproj
  src/Testcontainers.K3s/Testcontainers.K3s.csproj
  src/Testcontainers.Kafka/Testcontainers.Kafka.csproj
  src/Testcontainers.Keycloak/Testcontainers.Keycloak.csproj
  src/Testcontainers.Kusto/Testcontainers.Kusto.csproj
  src/Testcontainers.LocalStack/Testcontainers.LocalStack.csproj
  src/Testcontainers.MariaDb/Testcontainers.MariaDb.csproj
  src/Testcontainers.Minio/Testcontainers.Minio.csproj
  src/Testcontainers.MongoDb/Testcontainers.MongoDb.csproj
  src/Testcontainers.MsSql/Testcontainers.MsSql.csproj
  src/Testcontainers.MySql/Testcontainers.MySql.csproj
  src/Testcontainers.Nats/Testcontainers.Nats.csproj
  src/Testcontainers.Neo4j/Testcontainers.Neo4j.csproj
  src/Testcontainers.Oracle/Testcontainers.Oracle.csproj
  src/Testcontainers.Papercut/Testcontainers.Papercut.csproj
  src/Testcontainers.PostgreSql/Testcontainers.PostgreSql.csproj
  src/Testcontainers.PubSub/Testcontainers.PubSub.csproj
  src/Testcontainers.RabbitMq/Testcontainers.RabbitMq.csproj
  src/Testcontainers.RavenDb/Testcontainers.RavenDb.csproj
  src/Testcontainers.Redis/Testcontainers.Redis.csproj
  src/Testcontainers.Redpanda/Testcontainers.Redpanda.csproj
  src/Testcontainers.SqlEdge/Testcontainers.SqlEdge.csproj
  src/Testcontainers.WebDriver/Testcontainers.WebDriver.csproj
  src/Testcontainers/Containers/ResourceReaper.cs
  src/Testcontainers/Containers/ResourceReaperException.cs
  src/Testcontainers/Testcontainers.csproj
Labels: enhancement

#1139 feat: Use built-in PEM certificate import on .NET 6 and onwards
  src/Testcontainers/Builders/MTlsEndpointAuthenticationProvider.cs
  src/Testcontainers/Polyfills/X509Certificate2.cs
  src/Testcontainers/Testcontainers.csproj
  tests/Testcontainers.Tests/Testcontainers.Tests.csproj
Labels: enhancement

#1116 chore: Ensure that stderr is empty after executing scripts
  src/Testcontainers.MariaDb/MariaDbBuilder.cs
  src/Testcontainers.MariaDb/MariaDbContainer.cs
  src/Testcontainers.MongoDb/MongoDbContainer.cs
  src/Testcontainers.MongoDb/MongoDbShellCommand.cs
  src/Testcontainers.MongoDb/Usings.cs
  src/Testcontainers.MySql/MySqlBuilder.cs
  src/Testcontainers.MySql/MySqlContainer.cs
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Builders/IContainerBuilder`2.cs
  src/Testcontainers/Clients/DockerApiClient.cs
  src/Testcontainers/Containers/ResourceReaperState.cs
  tests/Testcontainers.ClickHouse.Tests/ClickHouseContainerTest.cs
  tests/Testcontainers.CockroachDb.Tests/CockroachDbContainerTest.cs
  tests/Testcontainers.FirebirdSql.Tests/FirebirdSqlContainerTest.cs
  tests/Testcontainers.MariaDb.Tests/MariaDbContainerTest.cs
  tests/Testcontainers.MongoDb.Tests/MongoDbContainerTest.cs
  tests/Testcontainers.MsSql.Tests/MsSqlContainerTest.cs
  tests/Testcontainers.MySql.Tests/MySqlContainerTest.cs
  tests/Testcontainers.Oracle.Tests/OracleContainerTest.cs
  tests/Testcontainers.PostgreSql.Tests/PostgreSqlContainerTest.cs
  tests/Testcontainers.Redis.Tests/RedisContainerTest.cs
Labels: chore

#1144 fix(MySql): Create an empty `/var/lib/mysql-files` directory to prevent older versions from failing to start
  src/Testcontainers.MySql/MySqlBuilder.cs
  src/Testcontainers.MySql/MySqlContainer.cs
  tests/Testcontainers.MySql.Tests/MySqlContainerTest.cs
Labels: bug

#1146 chore: Remove obsolete members
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  src/Testcontainers/Containers/DockerContainer.cs
  src/Testcontainers/Containers/ResourceReaper.cs
  tests/Testcontainers.ResourceReaper.Tests/DefaultResourceReaperTest.cs
Labels: chore
