Repository testcontainers/testcontainers-dotnet, pull requests merged in 2024-04, with the labels that each got.

#1151 docs: Add reading file from a container
  docs/api/create_docker_container.md
Labels: documentation

#1156 refactor: Replace Azure SQL Edge with PostgreSQL
  examples/WeatherForecast/Directory.Packages.props
  examples/WeatherForecast/src/WeatherForecast.Contexts/WeatherDataContext.cs
  examples/WeatherForecast/src/WeatherForecast.Contexts/WeatherDataReadOnlyContext.cs
  examples/WeatherForecast/src/WeatherForecast.Entities/Temperature.cs
  examples/WeatherForecast/src/WeatherForecast.Entities/WeatherData.cs
  examples/WeatherForecast/src/WeatherForecast/Controllers/WeatherForecastController.cs
  examples/WeatherForecast/src/WeatherForecast/DatabaseContainer.cs
  examples/WeatherForecast/src/WeatherForecast/Pages/SevenDayWeatherForecast.razor
  examples/WeatherForecast/src/WeatherForecast/Program.cs
  examples/WeatherForecast/src/WeatherForecast/Usings.cs
  examples/WeatherForecast/src/WeatherForecast/WeatherForecast.csproj
  examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/Usings.cs
  examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecastTest.cs
  examples/WeatherForecast/tests/WeatherForecast.Tests/Usings.cs
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastContainer.cs
Labels: chore

#1162 feat: Include the container name in the reuse hash
  docs/api/resource_reuse.md
  src/Testcontainers/Configurations/Containers/ContainerConfiguration.cs
  tests/Testcontainers.Platform.Linux.Tests/ReusableResourceTest.cs
Labels: enhancement, breaking change

#1164 chore: Prevent ReusableResourceTest from leaking resources
  Directory.Packages.props
  tests/Testcontainers.Platform.Linux.Tests/ReusableResourceTest.cs
  tests/Testcontainers.Platform.Linux.Tests/Testcontainers.Platform.Linux.Tests.csproj
  tests/Testcontainers.Platform.Linux.Tests/Usings.cs
Labels: chore
