Repository testcontainers/testcontainers-dotnet, pull requests merged in 2024-02, with the labels that each got.

#1109 fix(CosmosDb): SSL connection could not be established
  src/Testcontainers.CosmosDb/CosmosDbBuilder.cs
Labels: bug

#1110 fix: Consider the timestamp in the log message wait strategy (read the correct log message chunk)
  .github/workflows/cicd.yml
  .github/workflows/test-report.yml
  Directory.Packages.props
  src/Testcontainers.Elasticsearch/ElasticsearchBuilder.cs
  src/Testcontainers.MongoDb/MongoDbBuilder.cs
  src/Testcontainers.PostgreSql/PostgreSqlBuilder.cs
  src/Testcontainers/Clients/DockerContainerOperations.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilMessageIsLogged.cs
  src/Testcontainers/Containers/DockerContainer.cs
  src/Testcontainers/Containers/IContainer.cs
  tests/Testcontainers.Commons/SharedContainerInstance.cs
  tests/Testcontainers.Commons/Testcontainers.Commons.csproj
  tests/Testcontainers.Commons/Usings.cs
  tests/Testcontainers.PostgreSql.Tests/PostgreSqlContainerTest.cs
  tests/Testcontainers.PostgreSql.Tests/Usings.cs
Labels: bug

#1111 chore: Use the `pg_isready` command to assess whether PostgreSQL is ready or not
  src/Testcontainers.PostgreSql/PostgreSqlBuilder.cs
Labels: chore

#1118 feat: Add URL-based resource mapping container builder API
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Builders/IContainerBuilder`2.cs
  src/Testcontainers/Configurations/Volumes/UriResourceMapping.cs
  tests/Testcontainers.Platform.Linux.Tests/TarOutputMemoryStreamTest.cs
Labels: enhancement

#1122 fix: Prevent .dockerignore entry from matching everything if it ends with globstart
  src/Testcontainers/Images/IgnoreFile.cs
  tests/Testcontainers.Tests/Fixtures/Images/IgnoreFileFixture.cs
Labels: bug

#1124 feat: Add remote container registry identity token support
  Directory.Packages.props
  examples/Flyway/Directory.Packages.props
  examples/WeatherForecast/Directory.Packages.props
  global.json
  src/Testcontainers.PostgreSql/PostgreSqlBuilder.cs
  src/Testcontainers/Builders/Base64Provider.cs
  tests/Testcontainers.Tests/Unit/Configurations/DockerRegistryAuthenticationProviderTest.cs
Labels: enhancement

#1126 fix: Prevent a `NullReferenceException` when pulling uncached base images to build an image
  src/Testcontainers/Clients/TestcontainersClient.cs
Labels: bug

#1129 feat: Embed symbols and enable continuous integration builds (deterministic source paths)
  Directory.Build.props
  build.cake
  tests/Directory.Build.props
Labels: enhancement

#1131 feat: Add Milvus module
  Directory.Packages.props
  Testcontainers.sln
  src/Testcontainers.Milvus/.editorconfig
  src/Testcontainers.Milvus/MilvusBuilder.cs
  src/Testcontainers.Milvus/MilvusConfiguration.cs
  src/Testcontainers.Milvus/MilvusContainer.cs
  src/Testcontainers.Milvus/Testcontainers.Milvus.csproj
  src/Testcontainers.Milvus/Usings.cs
  tests/Testcontainers.Milvus.Tests/.editorconfig
  tests/Testcontainers.Milvus.Tests/MilvusContainerTest.cs
  tests/Testcontainers.Milvus.Tests/Testcontainers.Milvus.Tests.csproj
  tests/Testcontainers.Milvus.Tests/Usings.cs
Labels: enhancement
