Repository testcontainers/testcontainers-dotnet, pull requests merged in 2024-09, with the labels that each got.

#1251 chore: Replace codeinclude with snippets
  docs/api/create_docker_container.md
  docs/custom_configuration/index.md
  docs/examples/aspnet.md
  docs/examples/dind.md
  docs/index.md
  docs/modules/_call_out_test_projects.txt
  docs/modules/elasticsearch.md
  docs/modules/index.md
  docs/modules/mongodb.md
  docs/modules/mssql.md
  docs/modules/neo4j.md
  docs/modules/postgres.md
  docs/modules/pulsar.md
  docs/modules/rabbitmq.md
  mkdocs.yml
  requirements.txt
  src/Testcontainers.Couchbase/CouchbaseService.cs
  src/Testcontainers/Configurations/TestcontainersSettings.cs
  tests/Testcontainers.Elasticsearch.Tests/ElasticsearchContainerTest.cs
  tests/Testcontainers.Elasticsearch.Tests/Testcontainers.Elasticsearch.Tests.csproj
  tests/Testcontainers.MongoDb.Tests/MongoDbContainerTest.cs
  tests/Testcontainers.MongoDb.Tests/Testcontainers.MongoDb.Tests.csproj
  tests/Testcontainers.MsSql.Tests/MsSqlContainerTest.cs
  tests/Testcontainers.MsSql.Tests/Testcontainers.MsSql.Tests.csproj
  tests/Testcontainers.Neo4j.Tests/Neo4jContainerTest.cs
  tests/Testcontainers.Neo4j.Tests/Testcontainers.Neo4j.Tests.csproj
  tests/Testcontainers.PostgreSql.Tests/PostgreSqlContainerTest.cs
  tests/Testcontainers.PostgreSql.Tests/Testcontainers.PostgreSql.Tests.csproj
  tests/Testcontainers.Pulsar.Tests/PulsarContainerTest.cs
  tests/Testcontainers.Pulsar.Tests/Testcontainers.Pulsar.Tests.csproj
  tests/Testcontainers.RabbitMq.Tests/RabbitMqContainerTest.cs
  tests/Testcontainers.RabbitMq.Tests/Testcontainers.RabbitMq.Tests.csproj
Labels: documentation, chore

#1232 chore: Apply fix for github.com/apache/pulsar/issues/22811 only for affected versions
  Directory.Packages.props
  docs/modules/index.md
  src/Testcontainers.MsSql/MsSqlBuilder.cs
  src/Testcontainers.Pulsar/PulsarBuilder.cs
  src/Testcontainers.Pulsar/PulsarContainer.cs
Labels: module, chore

#1254 fix: Throw exception if Docker resource does not exist instead of silently ignoring it
  src/Testcontainers/Clients/DockerContainerOperations.cs
  src/Testcontainers/Clients/DockerImageOperations.cs
  src/Testcontainers/Clients/DockerNetworkOperations.cs
  src/Testcontainers/Clients/DockerVolumeOperations.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Containers/DockerContainer.cs
Labels: bug

#1235 feat: Get Docker endpoint from Docker context
  docs/custom_configuration/index.md
  src/Testcontainers/Builders/DockerConfig.cs
  src/Testcontainers/Builders/DockerDesktopEndpointAuthenticationProvider.cs
  src/Testcontainers/Builders/DockerRegistryAuthenticationProvider.cs
  src/Testcontainers/Builders/RootlessUnixEndpointAuthenticationProvider.cs
  src/Testcontainers/Builders/SourceGenerationContext.cs
  src/Testcontainers/Builders/TestcontainersEndpointAuthenticationProvider.cs
  src/Testcontainers/Configurations/CustomConfiguration.cs
  src/Testcontainers/Configurations/EnvironmentConfiguration.cs
  src/Testcontainers/Configurations/ICustomConfiguration.cs
  src/Testcontainers/Configurations/PropertiesFileConfiguration.cs
  tests/Testcontainers.Commons/DockerCli.cs
  tests/Testcontainers.Tests/Unit/Builders/DockerConfigTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/CustomConfigurationTest.cs
  tests/Testcontainers.Tests/Unit/Configurations/DockerRegistryAuthenticationProviderTest.cs
Labels: enhancement

#1258 feat: Change visibility of `AccountName` and `AccountKey` to public, move to `AzuriteBuilder`
  src/Testcontainers.Azurite/AzuriteBuilder.cs
  src/Testcontainers.Azurite/AzuriteContainer.cs
Labels: enhancement

#1249 feat: Support digest in `IImage`, `DockerImage` and in the `WithImage(string)` implementation
  src/Testcontainers/Builders/DockerConfig.cs
  src/Testcontainers/Builders/SourceGenerationContext.cs
  src/Testcontainers/Clients/DockerImageOperations.cs
  src/Testcontainers/Images/DockerImage.cs
  tests/Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerTest.cs
  tests/Testcontainers.Tests/Unit/Images/TestcontainersImageTest.cs
Labels: enhancement

#1265 fix: Bump MSSQL image version, remove Azure SQL Edge and Papercut module
  Testcontainers.sln
  docs/modules/index.md
  src/Testcontainers.MsSql/MsSqlBuilder.cs
  src/Testcontainers.Papercut/.editorconfig
  src/Testcontainers.Papercut/PapercutBuilder.cs
  src/Testcontainers.Papercut/PapercutConfiguration.cs
  src/Testcontainers.Papercut/PapercutContainer.cs
  src/Testcontainers.Papercut/Testcontainers.Papercut.csproj
  src/Testcontainers.Papercut/Usings.cs
  src/Testcontainers.SqlEdge/.editorconfig
  src/Testcontainers.SqlEdge/SqlEdgeBuilder.cs
  src/Testcontainers.SqlEdge/SqlEdgeConfiguration.cs
  src/Testcontainers.SqlEdge/SqlEdgeContainer.cs
  src/Testcontainers.SqlEdge/Testcontainers.SqlEdge.csproj
  src/Testcontainers.SqlEdge/Usings.cs
  tests/Testcontainers.MsSql.Tests/MsSqlContainerTest.cs
  tests/Testcontainers.Papercut.Tests/.editorconfig
  tests/Testcontainers.Papercut.Tests/PapercutContainerTest.cs
  tests/Testcontainers.Papercut.Tests/Testcontainers.Papercut.Tests.csproj
  tests/Testcontainers.Papercut.Tests/Usings.cs
  tests/Testcontainers.SqlEdge.Tests/.editorconfig
  tests/Testcontainers.SqlEdge.Tests/SqlEdgeContainerTest.cs
  tests/Testcontainers.SqlEdge.Tests/Testcontainers.SqlEdge.Tests.csproj
  tests/Testcontainers.SqlEdge.Tests/Usings.cs
Labels: bug, breaking change
