Repository testcontainers/testcontainers-dotnet, pull requests merged in 2025-04, with the labels that each got.

#1416 feat: Add Socat container implementation
  src/Testcontainers/Builders/BuildConfiguration.cs
  src/Testcontainers/Containers/SocatBuilder.cs
  src/Testcontainers/Containers/SocatConfiguration.cs
  src/Testcontainers/Containers/SocatContainer.cs
  tests/Testcontainers.Commons/CommonImages.cs
  tests/Testcontainers.Platform.Linux.Tests/SocatContainerTest.cs
  tests/Testcontainers.Platform.Linux.Tests/Usings.cs
  tests/Testcontainers.WebDriver.Tests/WebDriverContainerTest.cs
Labels: enhancement

#1419 docs: Bump `testcontainers/helloworld` image in docs to version `1.2.0`
  docs/index.md
Labels: documentation

#1420 fix(Pulsar): Set memory limits
  src/Testcontainers.Pulsar/PulsarBuilder.cs
  tests/Testcontainers.Pulsar.Tests/PulsarContainerTest.cs
  tests/Testcontainers.Pulsar.Tests/Usings.cs
Labels: bug, chore

#1424 feat(ServiceBus): Add builder API to upload config file
  docs/modules/servicebus.md
  src/Testcontainers.ServiceBus/ServiceBusBuilder.cs
  src/Testcontainers.ServiceBus/Usings.cs
  tests/Testcontainers.ServiceBus.Tests/ServiceBusContainerTest.cs
  tests/Testcontainers.ServiceBus.Tests/Testcontainers.ServiceBus.Tests.csproj
  tests/Testcontainers.ServiceBus.Tests/custom-queue-config.json
Labels: enhancement

#1344 feat: Add Lowkey Vault module
  .github/workflows/cicd.yml
  Directory.Packages.props
  Testcontainers.sln
  docs/modules/index.md
  src/Testcontainers.LowkeyVault/.editorconfig
  src/Testcontainers.LowkeyVault/LowkeyVaultBuilder.cs
  src/Testcontainers.LowkeyVault/LowkeyVaultConfiguration.cs
  src/Testcontainers.LowkeyVault/LowkeyVaultContainer.cs
  src/Testcontainers.LowkeyVault/Testcontainers.LowkeyVault.csproj
  src/Testcontainers.LowkeyVault/Usings.cs
  tests/Testcontainers.LowkeyVault.Tests/.editorconfig
  tests/Testcontainers.LowkeyVault.Tests/LowkeyVaultContainerTest.cs
  tests/Testcontainers.LowkeyVault.Tests/Testcontainers.LowkeyVault.Tests.csproj
  tests/Testcontainers.LowkeyVault.Tests/Usings.cs
Labels: enhancement

#1432 fix(EventHubs): Support default consumer group name
  src/Testcontainers.EventHubs/EventHubsServiceConfiguration.cs
  tests/Testcontainers.EventHubs.Tests/EventHubsContainerTest.cs
  tests/Testcontainers.EventHubs.Tests/Usings.cs
Labels: bug, enhancement

#1433 fix: Change predicate that it does not always evaluate to true
  src/Testcontainers.EventHubs/EventHubsServiceConfiguration.cs
  src/Testcontainers/Images/IImageExtensions.cs
Labels: bug

#1434 chore: Bump CI .NET SDK and Cake version
  .cake-scripts/version.cake
  .config/dotnet-tools.json
  build.cake
  global.json
  src/Testcontainers.EventHubs/EventHubsServiceConfiguration.cs
  tests/Testcontainers.EventHubs.Tests/EventHubsContainerTest.cs
Labels: chore

#1431 feat: Allow canceling container start in xUnit.net v3 fixtures
  Directory.Packages.props
  src/Testcontainers.Xunit/ContainerLifetime.cs
  src/Testcontainers.Xunit/Testcontainers.Xunit.csproj
  src/Testcontainers.XunitV3/Testcontainers.XunitV3.csproj
Labels: enhancement

#1099 feat: Add Ollama module
  .github/workflows/cicd.yml
  Directory.Packages.props
  Testcontainers.sln
  src/Testcontainers.Ollama/.editorconfig
  src/Testcontainers.Ollama/OllamaBuilder.cs
  src/Testcontainers.Ollama/OllamaConfiguration.cs
  src/Testcontainers.Ollama/OllamaContainer.cs
  src/Testcontainers.Ollama/Testcontainers.Ollama.csproj
  src/Testcontainers.Ollama/Usings.cs
  tests/Testcontainers.Ollama.Tests/.editorconfig
  tests/Testcontainers.Ollama.Tests/OllamaContainerTests.cs
  tests/Testcontainers.Ollama.Tests/Testcontainers.Ollama.Tests.csproj
  tests/Testcontainers.Ollama.Tests/Usings.cs
Labels: enhancement, module

#1401 feat: Add a wait strategy that waits until the ADO.NET database is available
  docs/modules/cassandra.md
  docs/modules/db2.md
  docs/modules/mssql.md
  docs/modules/postgres.md
  docs/modules/pulsar.md
  docs/modules/qdrant.md
  src/Testcontainers.Cassandra/CassandraContainer.cs
  src/Testcontainers.EventHubs/Usings.cs
  src/Testcontainers/Configurations/WaitStrategies/IWaitForContainerOS.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilDatabaseIsAvailable.cs
  src/Testcontainers/Configurations/WaitStrategies/WaitForContainerOS.cs
  tests/Testcontainers.Cassandra.Tests/CassandraContainerTest.cs
  tests/Testcontainers.Cassandra.Tests/Testcontainers.Cassandra.Tests.csproj
  tests/Testcontainers.Cassandra.Tests/Usings.cs
  tests/Testcontainers.ClickHouse.Tests/ClickHouseContainerTest.cs
  tests/Testcontainers.ClickHouse.Tests/Testcontainers.ClickHouse.Tests.csproj
  tests/Testcontainers.ClickHouse.Tests/Usings.cs
  tests/Testcontainers.CockroachDb.Tests/CockroachDbContainerTest.cs
  tests/Testcontainers.CockroachDb.Tests/Testcontainers.CockroachDb.Tests.csproj
  tests/Testcontainers.CockroachDb.Tests/Usings.cs
  tests/Testcontainers.Db2.Tests/Db2ContainerTest.cs
  tests/Testcontainers.Db2.Tests/Testcontainers.Db2.Tests.csproj
  tests/Testcontainers.Db2.Tests/Usings.cs
  tests/Testcontainers.FirebirdSql.Tests/FirebirdSqlContainerTest.cs
  tests/Testcontainers.FirebirdSql.Tests/Testcontainers.FirebirdSql.Tests.csproj
  tests/Testcontainers.FirebirdSql.Tests/Usings.cs
  tests/Testcontainers.MariaDb.Tests/MariaDbContainerTest.cs
  tests/Testcontainers.MariaDb.Tests/Testcontainers.MariaDb.Tests.csproj
  tests/Testcontainers.MariaDb.Tests/Usings.cs
  tests/Testcontainers.MsSql.Tests/MsSqlContainerTest.cs
  tests/Testcontainers.MsSql.Tests/Testcontainers.MsSql.Tests.csproj
  tests/Testcontainers.MsSql.Tests/Usings.cs
  tests/Testcontainers.MySql.Tests/MySqlContainerTest.cs
  tests/Testcontainers.MySql.Tests/Testcontainers.MySql.Tests.csproj
  tests/Testcontainers.MySql.Tests/Usings.cs
  tests/Testcontainers.Oracle.Tests/OracleContainerTest.cs
  tests/Testcontainers.Oracle.Tests/Usings.cs
  tests/Testcontainers.PostgreSql.Tests/PostgreSqlContainerTest.cs
  tests/Testcontainers.PostgreSql.Tests/Usings.cs
  tests/Testcontainers.Qdrant.Tests/Usings.cs
Labels: enhancement
