Repository testcontainers/testcontainers-dotnet, pull requests merged in 2025-07, with the labels that each got.

#1480 feat: Add named pipe connection timeout custom configuration
  Directory.Packages.props
  docs/custom_configuration/index.md
  src/Testcontainers/Builders/DockerDesktopEndpointAuthenticationProvider.cs
  src/Testcontainers/Builders/TestcontainersEndpointAuthenticationProvider.cs
  src/Testcontainers/Configurations/AuthConfigs/DockerEndpointAuthenticationConfiguration.cs
  src/Testcontainers/Configurations/CustomConfiguration.cs
  src/Testcontainers/Configurations/EnvironmentConfiguration.cs
  src/Testcontainers/Configurations/ICustomConfiguration.cs
  src/Testcontainers/Configurations/PropertiesFileConfiguration.cs
  tests/Testcontainers.Tests/Unit/Configurations/CustomConfigurationTest.cs
Labels: enhancement

#1487 docs: Extend example copying files to a container
  docs/api/create_docker_container.md
Labels: documentation

#1485 feat: Support getting all mapped ports
  src/Testcontainers/Containers/DockerContainer.cs
  src/Testcontainers/Containers/IContainer.cs
  src/Testcontainers/Images/IgnoreFile.cs
  tests/Testcontainers.Platform.Linux.Tests/PortBindingTest.cs
Labels: enhancement

#1493 fix: Add tooling to inherit XML docs
  Directory.Build.props
  docs/api/create_docker_container.md
  src/Testcontainers/Configurations/WaitStrategies/IWaitUntil.cs
  src/Testcontainers/Configurations/WaitStrategies/IWaitWhile.cs
Labels: enhancement

#1499 fix: Use null-conditional operator to access FinishedAt
  src/Testcontainers/Containers/DockerContainer.cs
Labels: bug
