Repository testcontainers/testcontainers-dotnet, pull requests merged in 2025-05, with the labels that each got.

#1442 docs: Mention the xUnit.net v3 module (package)
  docs/test_frameworks/xunit_net.md
Labels: documentation

#1443 chore: Bump Docker.DotNet version to `3.128.1`
  .devcontainer/devcontainer.json
  Directory.Packages.props
  docs/test_frameworks/xunit_net.md
  src/Testcontainers/Builders/TlsCredentials.cs
  src/Testcontainers/Clients/ContainerConfigurationConverter.cs
  src/Testcontainers/Clients/DockerContainerOperations.cs
  src/Testcontainers/Configurations/WaitStrategies/UntilMessageIsLogged.cs
  tests/Testcontainers.Pulsar.Tests/PulsarContainerTest.cs
  tests/Testcontainers.Xunit.Tests/PostgreSqlContainer.cs
Labels: chore

#1437 chore: Replace Cake .NET Tool with Cake Frosting
  .cake-scripts/credentials.cake
  .cake-scripts/parameters.cake
  .cake-scripts/paths.cake
  .cake-scripts/projects.cake
  .cake-scripts/version.cake
  .config/dotnet-tools.json
  .github/workflows/cicd.yml
  .gitignore
  Directory.Packages.props
  build.cake
  build.ps1
  build.sh
  build/.editorconfig
  build/Build.csproj
  build/Credentials.cs
  build/Parameters.cs
  build/Paths.cs
  build/Program.cs
  build/Projects.cs
  build/Tasks.cs
  build/Usings.cs
  build/Version.cs
  cake.config
  docs/contributing.md
Labels: chore

#1263 feat: Improve error reporting when loading the Docker configuration file
  src/Testcontainers/Builders/DockerConfig.cs
  src/Testcontainers/Builders/DockerConfigurationException.cs
  src/Testcontainers/Builders/DockerDesktopEndpointAuthenticationProvider.cs
  src/Testcontainers/Builders/RootlessUnixEndpointAuthenticationProvider.cs
  tests/Testcontainers.Tests/Unit/Builders/DockerConfigTest.cs
Labels: enhancement

#1308 feat: Throw `DockerUnavailableException` when Docker is not available
  src/Testcontainers/Builders/AbstractBuilder`4.cs
  src/Testcontainers/Builders/DockerEndpointAuthenticationProvider.cs
  src/Testcontainers/Builders/DockerUnavailableException.cs
  src/Testcontainers/Configurations/TestcontainersSettings.cs
Labels: enhancement

#1448 feat: Add `Task<ExecResult>` extension method `ThrowOnFailure`
  src/Testcontainers/Containers/ExecFailedException.cs
  src/Testcontainers/Containers/ExecResultExtensions.cs
  tests/Testcontainers.Platform.Linux.Tests/ExecFailedExceptionTest.cs
  tests/Testcontainers.Platform.Linux.Tests/ExecResultExtensionsTest.cs
Labels: enhancement

#1450 chore: Remove Sonar findings
  build/Parameters.cs
  src/Testcontainers/Containers/ExecFailedException.cs
  src/Testcontainers/Containers/ExecResultExtensions.cs
  tests/Testcontainers.ActiveMq.Tests/ArtemisContainerTest.cs
  tests/Testcontainers.Azurite.Tests/AzuriteContainerTest.cs
  tests/Testcontainers.Commons/DockerCli.cs
  tests/Testcontainers.Db2.Tests/DeclineLicenseAgreementTest.cs
  tests/Testcontainers.EventHubs.Tests/EventHubsContainerTest.cs
  tests/Testcontainers.Kafka.Tests/KafkaContainerNetworkTest.cs
  tests/Testcontainers.Kafka.Tests/KafkaContainerRegistryTest.cs
  tests/Testcontainers.Keycloak.Tests/KeycloakContainerTest.cs
  tests/Testcontainers.Keycloak.Tests/Usings.cs
  tests/Testcontainers.LocalStack.Tests/LocalStackContainerTest.cs
  tests/Testcontainers.LowkeyVault.Tests/LowkeyVaultContainerTest.cs
  tests/Testcontainers.Milvus.Tests/MilvusContainerTest.cs
  tests/Testcontainers.Milvus.Tests/Usings.cs
  tests/Testcontainers.MongoDb.Tests/MongoDbContainerTest.cs
  tests/Testcontainers.MongoDb.Tests/Usings.cs
  tests/Testcontainers.Nats.Tests/NatsContainerTest.cs
  tests/Testcontainers.Neo4j.Tests/Neo4jContainerTest.cs
  tests/Testcontainers.Ollama.Tests/OllamaContainerTest.cs
  tests/Testcontainers.Ollama.Tests/Usings.cs
  tests/Testcontainers.Platform.Linux.Tests/AcceptLicenseAgreementTest.cs
  tests/Testcontainers.Platform.Linux.Tests/ExecFailedExceptionTest.cs
  tests/Testcontainers.Platform.Linux.Tests/ExecResultExtensionsTest.cs
  tests/Testcontainers.Platform.Linux.Tests/LoggerTest.cs
  tests/Testcontainers.Platform.Linux.Tests/PauseUnpauseTest.cs
  tests/Testcontainers.Platform.Linux.Tests/PortForwardingTest.cs
  tests/Testcontainers.Platform.Linux.Tests/ReusableResourceTest.cs
  tests/Testcontainers.Platform.Linux.Tests/TarOutputMemoryStreamTest.cs
  tests/Testcontainers.Platform.Linux.Tests/WaitStrategyTest.cs
  tests/Testcontainers.Platform.Windows.Tests/Usings.cs
  tests/Testcontainers.Platform.Windows.Tests/WindowsContainerTest.cs
  tests/Testcontainers.Pulsar.Tests/PulsarContainerTest.cs
  tests/Testcontainers.Pulsar.Tests/Usings.cs
  tests/Testcontainers.ServiceBus.Tests/DeclineLicenseAgreementTest.cs
  tests/Testcontainers.ServiceBus.Tests/ServiceBusContainerTest.cs
  tests/Testcontainers.Tests/Fixtures/Containers/Unix/ProtectDockerDaemonSocket.cs
  tests/Testcontainers.Tests/Fixtures/Images/DockerImageFixture.cs
  tests/Testcontainers.WebDriver.Tests/WebDriverContainerTest.cs
  tests/Testcontainers.Xunit.Tests/PostgreSqlContainer.cs
  tests/Testcontainers.Xunit.Tests/RedisContainerTest`1.cs
  tests/Testcontainers.Xunit.Tests/RedisContainerTest`2.cs
  tests/Testcontainers.Xunit.Tests/Usings.cs
Labels: chore
