Repository testcontainers/testcontainers-dotnet, pull requests merged in 2025-03, with the labels that each got.

#1398 feat(EventHubs, ServiceBus): Replace wait strategy with HTTP health check
  src/Testcontainers.Db2/Db2Container.cs
  src/Testcontainers.EventHubs/EventHubsBuilder.cs
  src/Testcontainers.ServiceBus/ServiceBusBuilder.cs
  src/Testcontainers/Containers/DockerContainer.cs
  src/Testcontainers/Images/DockerfileArchive.cs
Labels: enhancement, chore

#1149 feat: Add Qdrant module
  .github/workflows/cicd.yml
  Directory.Packages.props
  Testcontainers.sln
  docs/modules/index.md
  docs/modules/qdrant.md
  mkdocs.yml
  src/Testcontainers.Qdrant/.editorconfig
  src/Testcontainers.Qdrant/QdrantBuilder.cs
  src/Testcontainers.Qdrant/QdrantConfiguration.cs
  src/Testcontainers.Qdrant/QdrantContainer.cs
  src/Testcontainers.Qdrant/Testcontainers.Qdrant.csproj
  src/Testcontainers.Qdrant/Usings.cs
  tests/Testcontainers.Qdrant.Tests/.editorconfig
  tests/Testcontainers.Qdrant.Tests/PemCertificate.cs
  tests/Testcontainers.Qdrant.Tests/QdrantDefaultContainerTest.cs
  tests/Testcontainers.Qdrant.Tests/QdrantSecureContainerTest.cs
  tests/Testcontainers.Qdrant.Tests/Testcontainers.Qdrant.Tests.csproj
  tests/Testcontainers.Qdrant.Tests/Usings.cs
Labels: enhancement, module

#1400 feat(Keycloak): Support admin bootstrapping for version 26 onwards
  src/Testcontainers.Keycloak/KeycloakBuilder.cs
  tests/Testcontainers.Keycloak.Tests/KeycloakContainerTest.cs
Labels: enhancement

#1402 docs: Add Bitbucket Pipelines configuration
  docs/cicd/index.md
Labels: documentation

#1410 chore: Use Docker Compose to host documentation locally
  compose.yml
  docs/contributing_docs.md
Labels: chore

#1413 fix: Add Docker Hub image name prefix to image builder API WithName(IImage)
  docs/examples/dind.md
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Builders/IImageFromDockerfileBuilder`1.cs
  src/Testcontainers/Builders/ImageFromDockerfileBuilder.cs
  src/Testcontainers/Images/IImageExtensions.cs
Labels: bug

#1414 docs: Add binding redirects doc for .NET framework
  docs/cicd/index.md
  docs/dind/index.md
  docs/full_framework/index.md
  mkdocs.yml
Labels: documentation
