Repository testcontainers/testcontainers-dotnet, pull requests merged in 2025-01, with the labels that each got.

#1328 feat: Add NAT driver network configuration
  src/Testcontainers.Pulsar/PulsarBuilder.cs
  src/Testcontainers/Configurations/Networks/NetworkDriver.cs
Labels: enhancement

#1315 feat: Add pausing and unpausing container
  src/Testcontainers/Clients/DockerContainerOperations.cs
  src/Testcontainers/Clients/IDockerContainerOperations.cs
  src/Testcontainers/Clients/ITestcontainersClient.cs
  src/Testcontainers/Clients/TestcontainersClient.cs
  src/Testcontainers/Containers/DockerContainer.cs
  src/Testcontainers/Containers/IContainer.cs
  src/Testcontainers/Logging.cs
  tests/Testcontainers.Platform.Linux.Tests/PauseUnpauseTest.cs
  tests/Testcontainers.Platform.Linux.Tests/Usings.cs
Labels: enhancement

#1316 feat: Add network support to the Kafka container
  Directory.Packages.props
  src/Testcontainers.Kafka/KafkaBuilder.cs
  src/Testcontainers.Kafka/KafkaConfiguration.cs
  src/Testcontainers.Kafka/KafkaContainer.cs
  src/Testcontainers.Kafka/Usings.cs
  tests/Testcontainers.Kafka.Tests/KafkaContainerNetworkTest.cs
  tests/Testcontainers.Kafka.Tests/KafkaContainerRegistryTest.cs
  tests/Testcontainers.Kafka.Tests/Testcontainers.Kafka.Tests.csproj
  tests/Testcontainers.Kafka.Tests/Usings.cs
Labels: bug, enhancement

#1355 fix(Pulsar): Support Apache Pulsar 4
  src/Testcontainers.Pulsar/PulsarBuilder.cs
  src/Testcontainers.Pulsar/PulsarContainer.cs
  tests/Testcontainers.Pulsar.Tests/PulsarContainerTest.cs
Labels: enhancement, module
