Repository testcontainers/testcontainers-dotnet, pull requests merged in 2025-02, with the labels that each got.

#1356 feat: Add Weaviate module
  .github/workflows/cicd.yml
  Testcontainers.dic
  Testcontainers.sln
  Testcontainers.sln.DotSettings
  src/Testcontainers.Weaviate/.editorconfig
  src/Testcontainers.Weaviate/Testcontainers.Weaviate.csproj
  src/Testcontainers.Weaviate/Usings.cs
  src/Testcontainers.Weaviate/WeaviateBuilder.cs
  src/Testcontainers.Weaviate/WeaviateConfiguration.cs
  src/Testcontainers.Weaviate/WeaviateContainer.cs
  tests/Testcontainers.Weaviate.Tests/.editorconfig
  tests/Testcontainers.Weaviate.Tests/Testcontainers.Weaviate.Tests.csproj
  tests/Testcontainers.Weaviate.Tests/Usings.cs
  tests/Testcontainers.Weaviate.Tests/WeaviateContainerTest.cs
Labels: enhancement, module

#1357 chore: Algin module configurations
  .node-version
  src/Testcontainers.DynamoDb/DynamoDbBuilder.cs
  src/Testcontainers.EventStoreDb/EventStoreDbBuilder.cs
  src/Testcontainers.FakeGcsServer/FakeGcsServerBuilder.cs
  src/Testcontainers.LocalStack/LocalStackBuilder.cs
  src/Testcontainers.Minio/MinioBuilder.cs
  tests/Testcontainers.Keycloak.Tests/KeycloakContainerTest.cs
  tests/Testcontainers.Nats.Tests/NatsContainerTest.cs
  tests/Testcontainers.Pulsar.Tests/PulsarContainerTest.cs
Labels: chore

#1335 feat(ServiceBus): Add support to use existing MSSQL container instances
  src/Testcontainers.ServiceBus/ServiceBusBuilder.cs
  src/Testcontainers.ServiceBus/Usings.cs
  src/Testcontainers/Builders/IContainerBuilder`2.cs
  tests/Testcontainers.ServiceBus.Tests/ServiceBusContainerTest.cs
  tests/Testcontainers.ServiceBus.Tests/Usings.cs
Labels: enhancement, module

#1363 chore: Remove binding of ports to IPv4 only
  src/Testcontainers/Clients/ContainerConfigurationConverter.cs
Labels: bug, chore

#1362 feat: Add SFTP module
  .github/workflows/cicd.yml
  Testcontainers.sln
  src/Testcontainers.Sftp/.editorconfig
  src/Testcontainers.Sftp/SftpBuilder.cs
  src/Testcontainers.Sftp/SftpConfiguration.cs
  src/Testcontainers.Sftp/SftpContainer.cs
  src/Testcontainers.Sftp/Testcontainers.Sftp.csproj
  src/Testcontainers.Sftp/Usings.cs
  tests/Testcontainers.Sftp.Tests/.editorconfig
  tests/Testcontainers.Sftp.Tests/SftpContainerTest.cs
  tests/Testcontainers.Sftp.Tests/Testcontainers.Sftp.Tests.csproj
  tests/Testcontainers.Sftp.Tests/Usings.cs
Labels: enhancement, module

#1368 chore: Set PackageLicenseExpression property to MIT
  Directory.Build.props
Labels: chore

#1369 fix(MongoDb): Evaluate replica set status in wait strategy
  Directory.Packages.props
  src/Testcontainers.MongoDb/MongoDbBuilder.cs
  src/Testcontainers.MongoDb/MongoDbContainer.cs
  tests/Testcontainers.MongoDb.Tests/MongoDbContainerTest.cs
Labels: bug

#1237 feat: Add Db2 module
  .github/workflows/cicd.yml
  Directory.Packages.props
  Testcontainers.sln
  docs/modules/db2.md
  mkdocs.yml
  src/Testcontainers.Db2/.editorconfig
  src/Testcontainers.Db2/Db2Builder.cs
  src/Testcontainers.Db2/Db2Configuration.cs
  src/Testcontainers.Db2/Db2Container.cs
  src/Testcontainers.Db2/Testcontainers.Db2.csproj
  src/Testcontainers.Db2/Usings.cs
  tests/Testcontainers.Db2.Tests/.editorconfig
  tests/Testcontainers.Db2.Tests/Db2ContainerTest.cs
  tests/Testcontainers.Db2.Tests/Testcontainers.Db2.Tests.csproj
  tests/Testcontainers.Db2.Tests/Testcontainers.Db2.Tests.targets
  tests/Testcontainers.Db2.Tests/Usings.cs
  tests/Testcontainers.Db2.Tests/linux.runsettings
Labels: enhancement, module

#1370 chore: Add WithAcceptLicenseAgreement(bool) to container builder
  src/Testcontainers.Db2/Db2Builder.cs
  src/Testcontainers.Neo4j/Neo4jBuilder.cs
  src/Testcontainers.Pulsar/Usings.cs
  src/Testcontainers.ServiceBus/ServiceBusBuilder.cs
  src/Testcontainers.ServiceBus/Usings.cs
  src/Testcontainers/Builders/Base64Provider.cs
  src/Testcontainers/Builders/ContainerBuilder`3.cs
  src/Testcontainers/Builders/CredsHelperProvider.cs
  src/Testcontainers/Builders/CredsStoreProvider.cs
  src/Testcontainers/Builders/IContainerBuilder`2.cs
  tests/Testcontainers.Db2.Tests/DeclineLicenseAgreementTest.cs
  tests/Testcontainers.Db2.Tests/Usings.cs
  tests/Testcontainers.Kafka.Tests/Usings.cs
  tests/Testcontainers.Platform.Linux.Tests/AcceptLicenseAgreementTest.cs
  tests/Testcontainers.ServiceBus.Tests/DeclineLicenseAgreementTest.cs
  tests/Testcontainers.ServiceBus.Tests/Usings.cs
Labels: chore

#1371 chore: Add support for macOS in Testcontainers.Db2.Tests
  Directory.Packages.props
  tests/Testcontainers.Db2.Tests/Testcontainers.Db2.Tests.csproj
Labels: chore

#1373 feat: Add EventHubs module
  .github/workflows/cicd.yml
  Directory.Packages.props
  Testcontainers.sln
  docs/modules/index.md
  src/Testcontainers.Azurite/AzuriteContainer.cs
  src/Testcontainers.EventHubs/.editorconfig
  src/Testcontainers.EventHubs/EventHubsBuilder.cs
  src/Testcontainers.EventHubs/EventHubsConfiguration.cs
  src/Testcontainers.EventHubs/EventHubsContainer.cs
  src/Testcontainers.EventHubs/EventHubsServiceConfiguration.cs
  src/Testcontainers.EventHubs/Testcontainers.EventHubs.csproj
  src/Testcontainers.EventHubs/Usings.cs
  tests/Testcontainers.EventHubs.Tests/.editorconfig
  tests/Testcontainers.EventHubs.Tests/EventHubsContainerTest.cs
  tests/Testcontainers.EventHubs.Tests/Testcontainers.EventHubs.Tests.csproj
  tests/Testcontainers.EventHubs.Tests/Usings.cs
  tests/Testcontainers.ServiceBus.Tests/ServiceBusContainerTest.cs
Labels: enhancement, module

#1367 feat: Add Apache Cassandra module
  .github/workflows/cicd.yml
  Directory.Packages.props
  Testcontainers.sln
  docs/modules/index.md
  src/Testcontainers.Cassandra/.editorconfig
  src/Testcontainers.Cassandra/CassandraBuilder.cs
  src/Testcontainers.Cassandra/CassandraConfiguration.cs
  src/Testcontainers.Cassandra/CassandraContainer.cs
  src/Testcontainers.Cassandra/Testcontainers.Cassandra.csproj
  src/Testcontainers.Cassandra/Usings.cs
  tests/Testcontainers.Cassandra.Tests/.editorconfig
  tests/Testcontainers.Cassandra.Tests/CassandraContainerTest.cs
  tests/Testcontainers.Cassandra.Tests/Testcontainers.Cassandra.Tests.csproj
  tests/Testcontainers.Cassandra.Tests/Usings.cs
Labels: enhancement, module

#1374 chore: Remove code smells and bump dependencies
  Directory.Packages.props
  docs/modules/index.md
  src/Testcontainers.EventHubs/EventHubsBuilder.cs
  src/Testcontainers.EventHubs/EventHubsContainer.cs
  src/Testcontainers.ServiceBus/ServiceBusBuilder.cs
  src/Testcontainers.Sftp/SftpBuilder.cs
  tests/Testcontainers.Pulsar.Tests/PulsarContainerTest.cs
  tests/Testcontainers.Tests/ContinuousIntegration/JobsTest.cs
Labels: chore

#1378 chore: Remove `SharedContainerInstance` and use `ContainerFixture` instead
  tests/Testcontainers.Commons/SharedContainerInstance.cs
  tests/Testcontainers.Commons/Testcontainers.Commons.csproj
  tests/Testcontainers.Commons/Usings.cs
  tests/Testcontainers.PostgreSql.Tests/PostgreSqlContainerTest.cs
  tests/Testcontainers.PostgreSql.Tests/Testcontainers.PostgreSql.Tests.csproj
  tests/Testcontainers.PostgreSql.Tests/Usings.cs
Labels: chore

#1379 chore: Update examples implementations
  examples/Flyway/Directory.Packages.props
  examples/Respawn/Directory.Packages.props
  examples/WeatherForecast/Directory.Packages.props
  examples/WeatherForecast/src/WeatherForecast.Repositories/Usings.cs
  examples/WeatherForecast/src/WeatherForecast/Program.cs
  examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/Usings.cs
  examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecastTest.cs
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastContainer.cs
  examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastImage.cs
Labels: chore

#1384 fix: Retrieve logs since `CreatedTime` for `UntilMessageIsLogged` wait strategy
  src/Testcontainers/Configurations/WaitStrategies/UntilMessageIsLogged.cs
Labels: bug
