Repository testcontainers/testcontainers-dotnet, pull requests merged in 2025-06, with the labels that each got.

#1446 feat: Add Typesense module
  .github/workflows/cicd.yml
  Testcontainers.sln
  docs/modules/index.md
  src/Testcontainers.Typesense/.editorconfig
  src/Testcontainers.Typesense/Testcontainers.Typesense.csproj
  src/Testcontainers.Typesense/TypesenseBuilder.cs
  src/Testcontainers.Typesense/TypesenseConfiguration.cs
  src/Testcontainers.Typesense/TypesenseContainer.cs
  src/Testcontainers.Typesense/Usings.cs
  tests/Testcontainers.Typesense.Tests/.editorconfig
  tests/Testcontainers.Typesense.Tests/Testcontainers.Typesense.Tests.csproj
  tests/Testcontainers.Typesense.Tests/TypesenseContainerTest.cs
  tests/Testcontainers.Typesense.Tests/Usings.cs
Labels: enhancement, module

#1421 docs(ClickHouse): Add example
  docs/modules/activemq.md
  docs/modules/clickhouse.md
  mkdocs.yml
  tests/Testcontainers.ActiveMq.Tests/ArtemisContainerTest.cs
  tests/Testcontainers.ClickHouse.Tests/ClickHouseContainerTest.cs
  tests/Testcontainers.ClickHouse.Tests/ClickHouseContainerTest.docs.cs
  tests/Testcontainers.ClickHouse.Tests/Testcontainers.ClickHouse.Tests.csproj
  tests/Testcontainers.ClickHouse.Tests/Usings.cs
Labels: documentation

#1395 feat: Add OpenSearch module
  .github/workflows/cicd.yml
  Directory.Packages.props
  Testcontainers.sln
  docs/modules/index.md
  docs/modules/opensearch.md
  mkdocs.yml
  src/Testcontainers.OpenSearch/.editorconfig
  src/Testcontainers.OpenSearch/OpenSearchBuilder.cs
  src/Testcontainers.OpenSearch/OpenSearchConfiguration.cs
  src/Testcontainers.OpenSearch/OpenSearchContainer.cs
  src/Testcontainers.OpenSearch/Testcontainers.OpenSearch.csproj
  src/Testcontainers.OpenSearch/Usings.cs
  tests/Testcontainers.OpenSearch.Tests/.editorconfig
  tests/Testcontainers.OpenSearch.Tests/OpenSearchBuilderTest.cs
  tests/Testcontainers.OpenSearch.Tests/OpenSearchContainerTest.cs
  tests/Testcontainers.OpenSearch.Tests/Testcontainers.OpenSearch.Tests.csproj
  tests/Testcontainers.OpenSearch.Tests/Usings.cs
Labels: enhancement, module

#1465 fix(ServiceBus): Remove container lifecycle overrides
  src/Testcontainers.ServiceBus/ServiceBusContainer.cs
Labels: bug

#1467 fix(Pulsar): Wait until the consumer becomes connected
  tests/Testcontainers.Pulsar.Tests/PulsarContainerTest.cs
Labels: bug
